using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
namespace GB698Cls
{
	public class AFN04_26 : iForm
	{
		private IContainer components = null;
		private Button button14;
		private Button button13;
		private Button button12;
		private Button button11;
		private Button button10;
		private Button button9;
		private Button button8;
		private Button button7;
		private Button button6;
		private Button button5;
		private Button button4;
		private Button button3;
		private Button button2;
		private Button button1;
		private Label label62;
		private TextBox textBox31;
		private Label label61;
		private Label label60;
		private TextBox textBox30;
		private Label label58;
		private TextBox textBox29;
		private Label label57;
		private Label label56;
		private TextBox textBox28;
		private GroupBox groupBox10;
		private Label label54;
		private TextBox textBox27;
		private Label label52;
		private TextBox textBox26;
		private Label label51;
		private Label label50;
		private TextBox textBox25;
		private GroupBox groupBox9;
		private Label label48;
		private TextBox textBox24;
		private Label label47;
		private Label label46;
		private TextBox textBox23;
		private Label label45;
		private Label label44;
		private TextBox textBox22;
		private GroupBox groupBox8;
		private Label label42;
		private TextBox textBox21;
		private Label label41;
		private Label label40;
		private TextBox textBox20;
		private Label label39;
		private Label label38;
		private TextBox textBox19;
		private GroupBox groupBox7;
		private Label label36;
		private TextBox textBox18;
		private Label label34;
		private TextBox textBox17;
		private Label label33;
		private TextBox textBox16;
		private GroupBox groupBox6;
		private Label label32;
		private TextBox textBox15;
		private Label label30;
		private TextBox textBox14;
		private Label label29;
		private Label label28;
		private TextBox textBox13;
		private GroupBox groupBox5;
		private GroupBox groupBox4;
		private GroupBox groupBox3;
		private GroupBox groupBox2;
		private GroupBox groupBox1;
		private Label label26;
		private TextBox textBox12;
		private Label label25;
		private Label label24;
		private TextBox textBox11;
		private Label label23;
		private Label label22;
		private TextBox textBox10;
		private Label label20;
		private TextBox textBox9;
		private Label label18;
		private TextBox textBox8;
		private Label label17;
		private Label label16;
		private TextBox textBox6;
		private Label label14;
		private TextBox textBox4;
		private Label label13;
		private Label label12;
		private Label label11;
		private Label label10;
		private Label label7;
		private Label label8;
		private TextBox textBox7;
		private Label label4;
		private Label label3;
		private TextBox textBox5;
		private Label label6;
		private TextBox textBox3;
		private Label label5;
		private TextBox textBox2;
		private Label label2;
		private TextBox textBox1;
		public AFN04_26()
		{
			this.InitializeComponent();
			base.HelpButton = true;
		}
		protected override void GetText()
		{
			this.Data = "";
			string text = string.Empty;
			text += base.OperaSend(this.textBox5.Text, 2, "A7");
			text += base.OperaSend(this.textBox2.Text, 2, "A7");
			text += base.OperaSend(this.textBox3.Text, 2, "A7");
			text += base.OperaSend(this.textBox4.Text, 2, "A7");
			text += base.OperaSend(this.textBox8.Text, 1, "BIN");
			text += this.textBox9.Text;
			text += base.OperaSend(this.textBox12.Text, 2, "A7");
			text += base.OperaSend(this.textBox11.Text, 1, "BIN");
			text += this.textBox10.Text;
			text += this.textBox15.Text;
			text += base.OperaSend(this.textBox14.Text, 1, "BIN");
			text += this.textBox13.Text;
			text += this.textBox7.Text;
			text += base.OperaSend(this.textBox6.Text, 1, "BIN");
			text += this.textBox1.Text;
			text += this.textBox18.Text;
			text += base.OperaSend(this.textBox17.Text, 1, "BIN");
			text += this.textBox16.Text;
			text += base.OperaSend(this.textBox21.Text, 3, "A23");
			text += base.OperaSend(this.textBox20.Text, 1, "BIN");
			text += this.textBox19.Text;
			text += base.OperaSend(this.textBox24.Text, 3, "A23");
			text += base.OperaSend(this.textBox23.Text, 1, "BIN");
			text += this.textBox22.Text;
			text += this.textBox27.Text;
			text += base.OperaSend(this.textBox26.Text, 1, "BIN");
			text += this.textBox25.Text;
			text += this.textBox30.Text;
			text += base.OperaSend(this.textBox29.Text, 1, "BIN");
			text += this.textBox28.Text;
			text += base.OperaSend(this.textBox31.Text, 1, "BIN");
			this.Data = text;
		}
		public override void SetText()
		{
			checked
			{
				if (!string.IsNullOrEmpty(this.Data))
				{
					string data = this.Data;
					int num = 0;
					this.textBox5.Text = base.OperaRec(data.Substring(num, 4), "A7");
					num += 4;
					this.textBox2.Text = base.OperaRec(data.Substring(num, 4), "A7");
					num += 4;
					this.textBox3.Text = base.OperaRec(data.Substring(num, 4), "A7");
					num += 4;
					this.textBox4.Text = base.OperaRec(data.Substring(num, 4), "A7");
					num += 4;
					this.textBox8.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox9.Text = data.Substring(num, 4);
					num += 4;
					this.textBox12.Text = base.OperaRec(data.Substring(num, 4), "A7");
					num += 4;
					this.textBox11.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox10.Text = data.Substring(num, 4);
					num += 4;
					this.textBox15.Text = data.Substring(num, 6);
					num += 6;
					this.textBox14.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox13.Text = data.Substring(num, 4);
					num += 4;
					this.textBox7.Text = data.Substring(num, 6);
					num += 6;
					this.textBox6.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox1.Text = data.Substring(num, 4);
					num += 4;
					this.textBox18.Text = data.Substring(num, 6);
					num += 6;
					this.textBox17.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox16.Text = data.Substring(num, 4);
					num += 4;
					this.textBox21.Text = base.OperaRec(data.Substring(num, 6), "A23");
					num += 6;
					this.textBox20.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox19.Text = data.Substring(num, 4);
					num += 4;
					this.textBox24.Text = base.OperaRec(data.Substring(num, 6), "A23");
					num += 6;
					this.textBox23.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox22.Text = data.Substring(num, 4);
					num += 4;
					this.textBox27.Text = data.Substring(num, 4);
					num += 4;
					this.textBox26.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox25.Text = data.Substring(num, 4);
					num += 4;
					this.textBox30.Text = data.Substring(num, 4);
					num += 4;
					this.textBox29.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
					this.textBox28.Text = data.Substring(num, 4);
					num += 4;
					this.textBox31.Text = base.OperaRec(data.Substring(num, 2), "BIN");
					num += 2;
				}
			}
		}
		private void Button1Click(object sender, EventArgs e)
		{
			iForm iForm = new A25();
			iForm.Data = this.textBox15.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox15.Text = iForm.Data;
		}
		private void Button2Click(object sender, EventArgs e)
		{
			iForm iForm = new A25();
			iForm.Data = this.textBox7.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox7.Text = iForm.Data;
		}
		private void Button3Click(object sender, EventArgs e)
		{
			iForm iForm = new A25();
			iForm.Data = this.textBox18.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox18.Text = iForm.Data;
		}
		private void Button4Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox9.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox9.Text = iForm.Data;
		}
		private void Button5Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox10.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox10.Text = iForm.Data;
		}
		private void Button6Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox13.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox13.Text = iForm.Data;
		}
		private void Button7Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox1.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox1.Text = iForm.Data;
		}
		private void Button8Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox16.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox16.Text = iForm.Data;
		}
		private void Button9Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox19.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox19.Text = iForm.Data;
		}
		private void Button10Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox22.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox22.Text = iForm.Data;
		}
		private void Button11Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox25.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox25.Text = iForm.Data;
		}
		private void Button12Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox28.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox28.Text = iForm.Data;
		}
		private void Button13Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox27.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox27.Text = iForm.Data;
		}
		private void Button14Click(object sender, EventArgs e)
		{
			iForm iForm = new A5();
			iForm.Data = this.textBox30.Text;
			iForm.SetText();
			iForm.ShowDialog();
			this.textBox30.Text = iForm.Data;
		}
		private void TextBox15TextChanged(object sender, EventArgs e)
		{
		}
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (this.components != null)
				{
					this.components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.groupBox1 = new GroupBox();
			this.label11 = new Label();
			this.textBox3 = new TextBox();
			this.label12 = new Label();
			this.label2 = new Label();
			this.textBox2 = new TextBox();
			this.label6 = new Label();
			this.label4 = new Label();
			this.textBox5 = new TextBox();
			this.label3 = new Label();
			this.groupBox2 = new GroupBox();
			this.button4 = new Button();
			this.textBox9 = new TextBox();
			this.label20 = new Label();
			this.label17 = new Label();
			this.textBox8 = new TextBox();
			this.label18 = new Label();
			this.label13 = new Label();
			this.textBox4 = new TextBox();
			this.label14 = new Label();
			this.groupBox3 = new GroupBox();
			this.button5 = new Button();
			this.textBox10 = new TextBox();
			this.label22 = new Label();
			this.label23 = new Label();
			this.textBox11 = new TextBox();
			this.label24 = new Label();
			this.label25 = new Label();
			this.textBox12 = new TextBox();
			this.label26 = new Label();
			this.groupBox5 = new GroupBox();
			this.button6 = new Button();
			this.button1 = new Button();
			this.textBox13 = new TextBox();
			this.label28 = new Label();
			this.label29 = new Label();
			this.textBox14 = new TextBox();
			this.label30 = new Label();
			this.textBox15 = new TextBox();
			this.label32 = new Label();
			this.groupBox6 = new GroupBox();
			this.button7 = new Button();
			this.button2 = new Button();
			this.textBox1 = new TextBox();
			this.label5 = new Label();
			this.label7 = new Label();
			this.textBox6 = new TextBox();
			this.label8 = new Label();
			this.textBox7 = new TextBox();
			this.label10 = new Label();
			this.groupBox4 = new GroupBox();
			this.button8 = new Button();
			this.button3 = new Button();
			this.textBox16 = new TextBox();
			this.label16 = new Label();
			this.label33 = new Label();
			this.textBox17 = new TextBox();
			this.label34 = new Label();
			this.textBox18 = new TextBox();
			this.label36 = new Label();
			this.groupBox7 = new GroupBox();
			this.button9 = new Button();
			this.textBox19 = new TextBox();
			this.label38 = new Label();
			this.label39 = new Label();
			this.textBox20 = new TextBox();
			this.label40 = new Label();
			this.label41 = new Label();
			this.textBox21 = new TextBox();
			this.label42 = new Label();
			this.groupBox8 = new GroupBox();
			this.button10 = new Button();
			this.textBox22 = new TextBox();
			this.label44 = new Label();
			this.label45 = new Label();
			this.textBox23 = new TextBox();
			this.label46 = new Label();
			this.label47 = new Label();
			this.textBox24 = new TextBox();
			this.label48 = new Label();
			this.groupBox9 = new GroupBox();
			this.button13 = new Button();
			this.button11 = new Button();
			this.textBox25 = new TextBox();
			this.label50 = new Label();
			this.label51 = new Label();
			this.textBox26 = new TextBox();
			this.label52 = new Label();
			this.textBox27 = new TextBox();
			this.label54 = new Label();
			this.groupBox10 = new GroupBox();
			this.button14 = new Button();
			this.button12 = new Button();
			this.textBox28 = new TextBox();
			this.label56 = new Label();
			this.label57 = new Label();
			this.textBox29 = new TextBox();
			this.label58 = new Label();
			this.textBox30 = new TextBox();
			this.label60 = new Label();
			this.label61 = new Label();
			this.textBox31 = new TextBox();
			this.label62 = new Label();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.groupBox3.SuspendLayout();
			this.groupBox5.SuspendLayout();
			this.groupBox6.SuspendLayout();
			this.groupBox4.SuspendLayout();
			this.groupBox7.SuspendLayout();
			this.groupBox8.SuspendLayout();
			this.groupBox9.SuspendLayout();
			this.groupBox10.SuspendLayout();
			base.SuspendLayout();
			this.groupBox1.Controls.Add(this.label11);
			this.groupBox1.Controls.Add(this.textBox3);
			this.groupBox1.Controls.Add(this.label12);
			this.groupBox1.Controls.Add(this.label2);
			this.groupBox1.Controls.Add(this.textBox2);
			this.groupBox1.Controls.Add(this.label6);
			this.groupBox1.Controls.Add(this.label4);
			this.groupBox1.Controls.Add(this.textBox5);
			this.groupBox1.Controls.Add(this.label3);
			this.groupBox1.Location = new Point(11, 3);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new Size(588, 44);
			this.groupBox1.TabIndex = 82;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "电压合格率判别参数";
			this.label11.AutoSize = true;
			this.label11.Location = new Point(562, 19);
			this.label11.Name = "label11";
			this.label11.Size = new Size(11, 12);
			this.label11.TabIndex = 69;
			this.label11.Text = "V";
			this.textBox3.Location = new Point(481, 16);
			this.textBox3.Name = "textBox3";
			this.textBox3.Size = new Size(75, 21);
			this.textBox3.TabIndex = 68;
			this.textBox3.Text = "0";
			this.label12.AutoSize = true;
			this.label12.Location = new Point(398, 19);
			this.label12.Name = "label12";
			this.label12.Size = new Size(77, 12);
			this.label12.TabIndex = 67;
			this.label12.Text = "电压断相门限";
			this.label2.AutoSize = true;
			this.label2.Location = new Point(370, 19);
			this.label2.Name = "label2";
			this.label2.Size = new Size(11, 12);
			this.label2.TabIndex = 66;
			this.label2.Text = "V";
			this.textBox2.Location = new Point(289, 16);
			this.textBox2.Name = "textBox2";
			this.textBox2.Size = new Size(75, 21);
			this.textBox2.TabIndex = 65;
			this.textBox2.Text = "0";
			this.label6.AutoSize = true;
			this.label6.Location = new Point(206, 19);
			this.label6.Name = "label6";
			this.label6.Size = new Size(77, 12);
			this.label6.TabIndex = 64;
			this.label6.Text = "电压合格下限";
			this.label4.AutoSize = true;
			this.label4.Location = new Point(180, 19);
			this.label4.Name = "label4";
			this.label4.Size = new Size(11, 12);
			this.label4.TabIndex = 63;
			this.label4.Text = "V";
			this.textBox5.Location = new Point(99, 16);
			this.textBox5.Name = "textBox5";
			this.textBox5.Size = new Size(75, 21);
			this.textBox5.TabIndex = 62;
			this.textBox5.Text = "0";
			this.label3.AutoSize = true;
			this.label3.Location = new Point(16, 19);
			this.label3.Name = "label3";
			this.label3.Size = new Size(77, 12);
			this.label3.TabIndex = 61;
			this.label3.Text = "电压合格上限";
			this.groupBox2.Controls.Add(this.button4);
			this.groupBox2.Controls.Add(this.textBox9);
			this.groupBox2.Controls.Add(this.label20);
			this.groupBox2.Controls.Add(this.label17);
			this.groupBox2.Controls.Add(this.textBox8);
			this.groupBox2.Controls.Add(this.label18);
			this.groupBox2.Controls.Add(this.label13);
			this.groupBox2.Controls.Add(this.textBox4);
			this.groupBox2.Controls.Add(this.label14);
			this.groupBox2.Location = new Point(11, 50);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new Size(588, 44);
			this.groupBox2.TabIndex = 83;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "过压判别参数";
			this.button4.Location = new Point(557, 15);
			this.button4.Name = "button4";
			this.button4.Size = new Size(16, 23);
			this.button4.TabIndex = 92;
			this.button4.UseVisualStyleBackColor = true;
			this.button4.Click += new EventHandler(this.Button4Click);
			this.textBox9.Location = new Point(504, 16);
			this.textBox9.Name = "textBox9";
			this.textBox9.ReadOnly = true;
			this.textBox9.Size = new Size(52, 21);
			this.textBox9.TabIndex = 80;
			this.textBox9.Text = "0000";
			this.label20.AutoSize = true;
			this.label20.Location = new Point(423, 19);
			this.label20.Name = "label20";
			this.label20.Size = new Size(77, 12);
			this.label20.TabIndex = 79;
			this.label20.Text = "越限恢复系数";
			this.label17.AutoSize = true;
			this.label17.Location = new Point(387, 19);
			this.label17.Name = "label17";
			this.label17.Size = new Size(23, 12);
			this.label17.TabIndex = 78;
			this.label17.Text = "min";
			this.textBox8.Location = new Point(354, 16);
			this.textBox8.Name = "textBox8";
			this.textBox8.Size = new Size(27, 21);
			this.textBox8.TabIndex = 77;
			this.textBox8.Text = "0";
			this.label18.AutoSize = true;
			this.label18.Location = new Point(274, 19);
			this.label18.Name = "label18";
			this.label18.Size = new Size(77, 12);
			this.label18.TabIndex = 76;
			this.label18.Text = "越限持续时间";
			this.label13.AutoSize = true;
			this.label13.Location = new Point(243, 19);
			this.label13.Name = "label13";
			this.label13.Size = new Size(11, 12);
			this.label13.TabIndex = 75;
			this.label13.Text = "V";
			this.textBox4.Location = new Point(153, 16);
			this.textBox4.Name = "textBox4";
			this.textBox4.Size = new Size(84, 21);
			this.textBox4.TabIndex = 74;
			this.textBox4.Text = "0";
			this.label14.AutoSize = true;
			this.label14.Location = new Point(16, 19);
			this.label14.Name = "label14";
			this.label14.Size = new Size(137, 12);
			this.label14.TabIndex = 73;
			this.label14.Text = "电压上上限（过压门限）";
			this.groupBox3.Controls.Add(this.button5);
			this.groupBox3.Controls.Add(this.textBox10);
			this.groupBox3.Controls.Add(this.label22);
			this.groupBox3.Controls.Add(this.label23);
			this.groupBox3.Controls.Add(this.textBox11);
			this.groupBox3.Controls.Add(this.label24);
			this.groupBox3.Controls.Add(this.label25);
			this.groupBox3.Controls.Add(this.textBox12);
			this.groupBox3.Controls.Add(this.label26);
			this.groupBox3.Location = new Point(11, 97);
			this.groupBox3.Name = "groupBox3";
			this.groupBox3.Size = new Size(588, 44);
			this.groupBox3.TabIndex = 84;
			this.groupBox3.TabStop = false;
			this.groupBox3.Text = "欠压判别参数";
			this.button5.Location = new Point(557, 14);
			this.button5.Name = "button5";
			this.button5.Size = new Size(16, 23);
			this.button5.TabIndex = 93;
			this.button5.UseVisualStyleBackColor = true;
			this.button5.Click += new EventHandler(this.Button5Click);
			this.textBox10.Location = new Point(504, 16);
			this.textBox10.Name = "textBox10";
			this.textBox10.ReadOnly = true;
			this.textBox10.Size = new Size(52, 21);
			this.textBox10.TabIndex = 89;
			this.textBox10.Text = "0000";
			this.label22.AutoSize = true;
			this.label22.Location = new Point(423, 19);
			this.label22.Name = "label22";
			this.label22.Size = new Size(77, 12);
			this.label22.TabIndex = 88;
			this.label22.Text = "越限恢复系数";
			this.label23.AutoSize = true;
			this.label23.Location = new Point(387, 19);
			this.label23.Name = "label23";
			this.label23.Size = new Size(23, 12);
			this.label23.TabIndex = 87;
			this.label23.Text = "min";
			this.textBox11.Location = new Point(354, 16);
			this.textBox11.Name = "textBox11";
			this.textBox11.Size = new Size(27, 21);
			this.textBox11.TabIndex = 86;
			this.textBox11.Text = "0";
			this.label24.AutoSize = true;
			this.label24.Location = new Point(274, 19);
			this.label24.Name = "label24";
			this.label24.Size = new Size(77, 12);
			this.label24.TabIndex = 85;
			this.label24.Text = "越限持续时间";
			this.label25.AutoSize = true;
			this.label25.Location = new Point(243, 19);
			this.label25.Name = "label25";
			this.label25.Size = new Size(11, 12);
			this.label25.TabIndex = 84;
			this.label25.Text = "V";
			this.textBox12.Location = new Point(153, 16);
			this.textBox12.Name = "textBox12";
			this.textBox12.Size = new Size(84, 21);
			this.textBox12.TabIndex = 83;
			this.textBox12.Text = "0";
			this.label26.AutoSize = true;
			this.label26.Location = new Point(16, 19);
			this.label26.Name = "label26";
			this.label26.Size = new Size(137, 12);
			this.label26.TabIndex = 82;
			this.label26.Text = "电压下下限（欠压门限）";
			this.groupBox5.Controls.Add(this.button6);
			this.groupBox5.Controls.Add(this.button1);
			this.groupBox5.Controls.Add(this.textBox13);
			this.groupBox5.Controls.Add(this.label28);
			this.groupBox5.Controls.Add(this.label29);
			this.groupBox5.Controls.Add(this.textBox14);
			this.groupBox5.Controls.Add(this.label30);
			this.groupBox5.Controls.Add(this.textBox15);
			this.groupBox5.Controls.Add(this.label32);
			this.groupBox5.Location = new Point(11, 144);
			this.groupBox5.Name = "groupBox5";
			this.groupBox5.Size = new Size(588, 44);
			this.groupBox5.TabIndex = 86;
			this.groupBox5.TabStop = false;
			this.groupBox5.Text = "过流判别参数";
			this.button6.Location = new Point(557, 15);
			this.button6.Name = "button6";
			this.button6.Size = new Size(16, 23);
			this.button6.TabIndex = 94;
			this.button6.UseVisualStyleBackColor = true;
			this.button6.Click += new EventHandler(this.Button6Click);
			this.button1.Location = new Point(238, 15);
			this.button1.Name = "button1";
			this.button1.Size = new Size(16, 23);
			this.button1.TabIndex = 91;
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new EventHandler(this.Button1Click);
			this.textBox13.Location = new Point(504, 16);
			this.textBox13.Name = "textBox13";
			this.textBox13.ReadOnly = true;
			this.textBox13.Size = new Size(52, 21);
			this.textBox13.TabIndex = 89;
			this.textBox13.Text = "0000";
			this.label28.AutoSize = true;
			this.label28.Location = new Point(423, 19);
			this.label28.Name = "label28";
			this.label28.Size = new Size(77, 12);
			this.label28.TabIndex = 88;
			this.label28.Text = "越限恢复系数";
			this.label29.AutoSize = true;
			this.label29.Location = new Point(387, 19);
			this.label29.Name = "label29";
			this.label29.Size = new Size(23, 12);
			this.label29.TabIndex = 87;
			this.label29.Text = "min";
			this.textBox14.Location = new Point(354, 16);
			this.textBox14.Name = "textBox14";
			this.textBox14.Size = new Size(27, 21);
			this.textBox14.TabIndex = 86;
			this.textBox14.Text = "0";
			this.label30.AutoSize = true;
			this.label30.Location = new Point(274, 19);
			this.label30.Name = "label30";
			this.label30.Size = new Size(77, 12);
			this.label30.TabIndex = 85;
			this.label30.Text = "越限持续时间";
			this.textBox15.Location = new Point(171, 16);
			this.textBox15.Name = "textBox15";
			this.textBox15.ReadOnly = true;
			this.textBox15.Size = new Size(66, 21);
			this.textBox15.TabIndex = 83;
			this.textBox15.Text = "000000";
			this.textBox15.TextChanged += new EventHandler(this.TextBox15TextChanged);
			this.label32.AutoSize = true;
			this.label32.Location = new Point(16, 19);
			this.label32.Name = "label32";
			this.label32.Size = new Size(149, 12);
			this.label32.TabIndex = 82;
			this.label32.Text = "相电流上上限（过流门限）";
			this.groupBox6.Controls.Add(this.button7);
			this.groupBox6.Controls.Add(this.button2);
			this.groupBox6.Controls.Add(this.textBox1);
			this.groupBox6.Controls.Add(this.label5);
			this.groupBox6.Controls.Add(this.label7);
			this.groupBox6.Controls.Add(this.textBox6);
			this.groupBox6.Controls.Add(this.label8);
			this.groupBox6.Controls.Add(this.textBox7);
			this.groupBox6.Controls.Add(this.label10);
			this.groupBox6.Location = new Point(11, 191);
			this.groupBox6.Name = "groupBox6";
			this.groupBox6.Size = new Size(588, 44);
			this.groupBox6.TabIndex = 87;
			this.groupBox6.TabStop = false;
			this.groupBox6.Text = "超额定电流判别参数";
			this.button7.Location = new Point(557, 15);
			this.button7.Name = "button7";
			this.button7.Size = new Size(16, 23);
			this.button7.TabIndex = 95;
			this.button7.UseVisualStyleBackColor = true;
			this.button7.Click += new EventHandler(this.Button7Click);
			this.button2.Location = new Point(238, 15);
			this.button2.Name = "button2";
			this.button2.Size = new Size(16, 23);
			this.button2.TabIndex = 92;
			this.button2.UseVisualStyleBackColor = true;
			this.button2.Click += new EventHandler(this.Button2Click);
			this.textBox1.Location = new Point(504, 16);
			this.textBox1.Name = "textBox1";
			this.textBox1.ReadOnly = true;
			this.textBox1.Size = new Size(52, 21);
			this.textBox1.TabIndex = 89;
			this.textBox1.Text = "0000";
			this.label5.AutoSize = true;
			this.label5.Location = new Point(423, 19);
			this.label5.Name = "label5";
			this.label5.Size = new Size(77, 12);
			this.label5.TabIndex = 88;
			this.label5.Text = "越限恢复系数";
			this.label7.AutoSize = true;
			this.label7.Location = new Point(387, 19);
			this.label7.Name = "label7";
			this.label7.Size = new Size(23, 12);
			this.label7.TabIndex = 87;
			this.label7.Text = "min";
			this.textBox6.Location = new Point(354, 16);
			this.textBox6.Name = "textBox6";
			this.textBox6.Size = new Size(27, 21);
			this.textBox6.TabIndex = 86;
			this.textBox6.Text = "0";
			this.label8.AutoSize = true;
			this.label8.Location = new Point(274, 19);
			this.label8.Name = "label8";
			this.label8.Size = new Size(77, 12);
			this.label8.TabIndex = 85;
			this.label8.Text = "越限持续时间";
			this.textBox7.Location = new Point(171, 16);
			this.textBox7.Name = "textBox7";
			this.textBox7.ReadOnly = true;
			this.textBox7.Size = new Size(66, 21);
			this.textBox7.TabIndex = 83;
			this.textBox7.Text = "000000";
			this.label10.AutoSize = true;
			this.label10.Location = new Point(16, 19);
			this.label10.Name = "label10";
			this.label10.Size = new Size(161, 12);
			this.label10.TabIndex = 82;
			this.label10.Text = "相电流上限（额定电流门限）";
			this.groupBox4.Controls.Add(this.button8);
			this.groupBox4.Controls.Add(this.button3);
			this.groupBox4.Controls.Add(this.textBox16);
			this.groupBox4.Controls.Add(this.label16);
			this.groupBox4.Controls.Add(this.label33);
			this.groupBox4.Controls.Add(this.textBox17);
			this.groupBox4.Controls.Add(this.label34);
			this.groupBox4.Controls.Add(this.textBox18);
			this.groupBox4.Controls.Add(this.label36);
			this.groupBox4.Location = new Point(11, 238);
			this.groupBox4.Name = "groupBox4";
			this.groupBox4.Size = new Size(588, 44);
			this.groupBox4.TabIndex = 88;
			this.groupBox4.TabStop = false;
			this.groupBox4.Text = "零序电流超限判别";
			this.button8.Location = new Point(557, 14);
			this.button8.Name = "button8";
			this.button8.Size = new Size(16, 23);
			this.button8.TabIndex = 96;
			this.button8.UseVisualStyleBackColor = true;
			this.button8.Click += new EventHandler(this.Button8Click);
			this.button3.Location = new Point(238, 15);
			this.button3.Name = "button3";
			this.button3.Size = new Size(16, 23);
			this.button3.TabIndex = 93;
			this.button3.UseVisualStyleBackColor = true;
			this.button3.Click += new EventHandler(this.Button3Click);
			this.textBox16.Location = new Point(504, 16);
			this.textBox16.Name = "textBox16";
			this.textBox16.ReadOnly = true;
			this.textBox16.Size = new Size(52, 21);
			this.textBox16.TabIndex = 89;
			this.textBox16.Text = "0000";
			this.label16.AutoSize = true;
			this.label16.Location = new Point(423, 19);
			this.label16.Name = "label16";
			this.label16.Size = new Size(77, 12);
			this.label16.TabIndex = 88;
			this.label16.Text = "越限恢复系数";
			this.label33.AutoSize = true;
			this.label33.Location = new Point(387, 19);
			this.label33.Name = "label33";
			this.label33.Size = new Size(23, 12);
			this.label33.TabIndex = 87;
			this.label33.Text = "min";
			this.textBox17.Location = new Point(354, 16);
			this.textBox17.Name = "textBox17";
			this.textBox17.Size = new Size(27, 21);
			this.textBox17.TabIndex = 86;
			this.textBox17.Text = "0";
			this.label34.AutoSize = true;
			this.label34.Location = new Point(274, 19);
			this.label34.Name = "label34";
			this.label34.Size = new Size(77, 12);
			this.label34.TabIndex = 85;
			this.label34.Text = "越限持续时间";
			this.textBox18.Location = new Point(99, 16);
			this.textBox18.Name = "textBox18";
			this.textBox18.ReadOnly = true;
			this.textBox18.Size = new Size(138, 21);
			this.textBox18.TabIndex = 83;
			this.textBox18.Text = "000000";
			this.label36.AutoSize = true;
			this.label36.Location = new Point(16, 19);
			this.label36.Name = "label36";
			this.label36.Size = new Size(77, 12);
			this.label36.TabIndex = 82;
			this.label36.Text = "零序电流上限";
			this.groupBox7.Controls.Add(this.button9);
			this.groupBox7.Controls.Add(this.textBox19);
			this.groupBox7.Controls.Add(this.label38);
			this.groupBox7.Controls.Add(this.label39);
			this.groupBox7.Controls.Add(this.textBox20);
			this.groupBox7.Controls.Add(this.label40);
			this.groupBox7.Controls.Add(this.label41);
			this.groupBox7.Controls.Add(this.textBox21);
			this.groupBox7.Controls.Add(this.label42);
			this.groupBox7.Location = new Point(11, 285);
			this.groupBox7.Name = "groupBox7";
			this.groupBox7.Size = new Size(588, 44);
			this.groupBox7.TabIndex = 89;
			this.groupBox7.TabStop = false;
			this.groupBox7.Text = "视在功率超上上限";
			this.button9.Location = new Point(557, 15);
			this.button9.Name = "button9";
			this.button9.Size = new Size(16, 23);
			this.button9.TabIndex = 97;
			this.button9.UseVisualStyleBackColor = true;
			this.button9.Click += new EventHandler(this.Button9Click);
			this.textBox19.Location = new Point(504, 16);
			this.textBox19.Name = "textBox19";
			this.textBox19.ReadOnly = true;
			this.textBox19.Size = new Size(52, 21);
			this.textBox19.TabIndex = 89;
			this.textBox19.Text = "0000";
			this.label38.AutoSize = true;
			this.label38.Location = new Point(423, 19);
			this.label38.Name = "label38";
			this.label38.Size = new Size(77, 12);
			this.label38.TabIndex = 88;
			this.label38.Text = "越限恢复系数";
			this.label39.AutoSize = true;
			this.label39.Location = new Point(387, 19);
			this.label39.Name = "label39";
			this.label39.Size = new Size(23, 12);
			this.label39.TabIndex = 87;
			this.label39.Text = "min";
			this.textBox20.Location = new Point(354, 16);
			this.textBox20.Name = "textBox20";
			this.textBox20.Size = new Size(27, 21);
			this.textBox20.TabIndex = 86;
			this.textBox20.Text = "0";
			this.label40.AutoSize = true;
			this.label40.Location = new Point(274, 19);
			this.label40.Name = "label40";
			this.label40.Size = new Size(77, 12);
			this.label40.TabIndex = 85;
			this.label40.Text = "越限持续时间";
			this.label41.AutoSize = true;
			this.label41.Location = new Point(239, 19);
			this.label41.Name = "label41";
			this.label41.Size = new Size(23, 12);
			this.label41.TabIndex = 84;
			this.label41.Text = "kVA";
			this.textBox21.Location = new Point(111, 16);
			this.textBox21.Name = "textBox21";
			this.textBox21.Size = new Size(126, 21);
			this.textBox21.TabIndex = 83;
			this.textBox21.Text = "0";
			this.label42.AutoSize = true;
			this.label42.Location = new Point(16, 19);
			this.label42.Name = "label42";
			this.label42.Size = new Size(89, 12);
			this.label42.TabIndex = 82;
			this.label42.Text = "视在功率上上限";
			this.groupBox8.Controls.Add(this.button10);
			this.groupBox8.Controls.Add(this.textBox22);
			this.groupBox8.Controls.Add(this.label44);
			this.groupBox8.Controls.Add(this.label45);
			this.groupBox8.Controls.Add(this.textBox23);
			this.groupBox8.Controls.Add(this.label46);
			this.groupBox8.Controls.Add(this.label47);
			this.groupBox8.Controls.Add(this.textBox24);
			this.groupBox8.Controls.Add(this.label48);
			this.groupBox8.Location = new Point(11, 333);
			this.groupBox8.Name = "groupBox8";
			this.groupBox8.Size = new Size(588, 44);
			this.groupBox8.TabIndex = 90;
			this.groupBox8.TabStop = false;
			this.groupBox8.Text = "视在功率超上限";
			this.button10.Location = new Point(557, 15);
			this.button10.Name = "button10";
			this.button10.Size = new Size(16, 23);
			this.button10.TabIndex = 98;
			this.button10.UseVisualStyleBackColor = true;
			this.button10.Click += new EventHandler(this.Button10Click);
			this.textBox22.Location = new Point(504, 16);
			this.textBox22.Name = "textBox22";
			this.textBox22.ReadOnly = true;
			this.textBox22.Size = new Size(52, 21);
			this.textBox22.TabIndex = 89;
			this.textBox22.Text = "0000";
			this.label44.AutoSize = true;
			this.label44.Location = new Point(423, 19);
			this.label44.Name = "label44";
			this.label44.Size = new Size(77, 12);
			this.label44.TabIndex = 88;
			this.label44.Text = "越限恢复系数";
			this.label45.AutoSize = true;
			this.label45.Location = new Point(387, 19);
			this.label45.Name = "label45";
			this.label45.Size = new Size(23, 12);
			this.label45.TabIndex = 87;
			this.label45.Text = "min";
			this.textBox23.Location = new Point(354, 16);
			this.textBox23.Name = "textBox23";
			this.textBox23.Size = new Size(27, 21);
			this.textBox23.TabIndex = 86;
			this.textBox23.Text = "0";
			this.label46.AutoSize = true;
			this.label46.Location = new Point(274, 19);
			this.label46.Name = "label46";
			this.label46.Size = new Size(77, 12);
			this.label46.TabIndex = 85;
			this.label46.Text = "越限持续时间";
			this.label47.AutoSize = true;
			this.label47.Location = new Point(239, 19);
			this.label47.Name = "label47";
			this.label47.Size = new Size(23, 12);
			this.label47.TabIndex = 84;
			this.label47.Text = "kVA";
			this.textBox24.Location = new Point(111, 16);
			this.textBox24.Name = "textBox24";
			this.textBox24.Size = new Size(126, 21);
			this.textBox24.TabIndex = 83;
			this.textBox24.Text = "0";
			this.label48.AutoSize = true;
			this.label48.Location = new Point(16, 19);
			this.label48.Name = "label48";
			this.label48.Size = new Size(77, 12);
			this.label48.TabIndex = 82;
			this.label48.Text = "视在功率上限";
			this.groupBox9.Controls.Add(this.button13);
			this.groupBox9.Controls.Add(this.button11);
			this.groupBox9.Controls.Add(this.textBox25);
			this.groupBox9.Controls.Add(this.label50);
			this.groupBox9.Controls.Add(this.label51);
			this.groupBox9.Controls.Add(this.textBox26);
			this.groupBox9.Controls.Add(this.label52);
			this.groupBox9.Controls.Add(this.textBox27);
			this.groupBox9.Controls.Add(this.label54);
			this.groupBox9.Location = new Point(11, 380);
			this.groupBox9.Name = "groupBox9";
			this.groupBox9.Size = new Size(588, 44);
			this.groupBox9.TabIndex = 91;
			this.groupBox9.TabStop = false;
			this.groupBox9.Text = "三相电压不平衡超限";
			this.button13.Location = new Point(237, 15);
			this.button13.Name = "button13";
			this.button13.Size = new Size(16, 23);
			this.button13.TabIndex = 101;
			this.button13.UseVisualStyleBackColor = true;
			this.button13.Click += new EventHandler(this.Button13Click);
			this.button11.Location = new Point(557, 15);
			this.button11.Name = "button11";
			this.button11.Size = new Size(16, 23);
			this.button11.TabIndex = 99;
			this.button11.UseVisualStyleBackColor = true;
			this.button11.Click += new EventHandler(this.Button11Click);
			this.textBox25.Location = new Point(504, 16);
			this.textBox25.Name = "textBox25";
			this.textBox25.ReadOnly = true;
			this.textBox25.Size = new Size(52, 21);
			this.textBox25.TabIndex = 89;
			this.textBox25.Text = "0000";
			this.label50.AutoSize = true;
			this.label50.Location = new Point(423, 19);
			this.label50.Name = "label50";
			this.label50.Size = new Size(77, 12);
			this.label50.TabIndex = 88;
			this.label50.Text = "越限恢复系数";
			this.label51.AutoSize = true;
			this.label51.Location = new Point(387, 19);
			this.label51.Name = "label51";
			this.label51.Size = new Size(23, 12);
			this.label51.TabIndex = 87;
			this.label51.Text = "min";
			this.textBox26.Location = new Point(354, 16);
			this.textBox26.Name = "textBox26";
			this.textBox26.Size = new Size(27, 21);
			this.textBox26.TabIndex = 86;
			this.textBox26.Text = "0";
			this.label52.AutoSize = true;
			this.label52.Location = new Point(274, 19);
			this.label52.Name = "label52";
			this.label52.Size = new Size(77, 12);
			this.label52.TabIndex = 85;
			this.label52.Text = "越限持续时间";
			this.textBox27.Location = new Point(135, 16);
			this.textBox27.Name = "textBox27";
			this.textBox27.ReadOnly = true;
			this.textBox27.Size = new Size(102, 21);
			this.textBox27.TabIndex = 83;
			this.textBox27.Text = "0000";
			this.label54.AutoSize = true;
			this.label54.Location = new Point(16, 19);
			this.label54.Name = "label54";
			this.label54.Size = new Size(113, 12);
			this.label54.TabIndex = 82;
			this.label54.Text = "三相电压不平衡限值";
			this.groupBox10.Controls.Add(this.button14);
			this.groupBox10.Controls.Add(this.button12);
			this.groupBox10.Controls.Add(this.textBox28);
			this.groupBox10.Controls.Add(this.label56);
			this.groupBox10.Controls.Add(this.label57);
			this.groupBox10.Controls.Add(this.textBox29);
			this.groupBox10.Controls.Add(this.label58);
			this.groupBox10.Controls.Add(this.textBox30);
			this.groupBox10.Controls.Add(this.label60);
			this.groupBox10.Location = new Point(11, 428);
			this.groupBox10.Name = "groupBox10";
			this.groupBox10.Size = new Size(588, 44);
			this.groupBox10.TabIndex = 92;
			this.groupBox10.TabStop = false;
			this.groupBox10.Text = "三相电流不平衡超限";
			this.button14.Location = new Point(237, 15);
			this.button14.Name = "button14";
			this.button14.Size = new Size(16, 23);
			this.button14.TabIndex = 102;
			this.button14.UseVisualStyleBackColor = true;
			this.button14.Click += new EventHandler(this.Button14Click);
			this.button12.Location = new Point(557, 14);
			this.button12.Name = "button12";
			this.button12.Size = new Size(16, 23);
			this.button12.TabIndex = 100;
			this.button12.UseVisualStyleBackColor = true;
			this.button12.Click += new EventHandler(this.Button12Click);
			this.textBox28.Location = new Point(504, 16);
			this.textBox28.Name = "textBox28";
			this.textBox28.ReadOnly = true;
			this.textBox28.Size = new Size(52, 21);
			this.textBox28.TabIndex = 89;
			this.textBox28.Text = "0000";
			this.label56.AutoSize = true;
			this.label56.Location = new Point(423, 19);
			this.label56.Name = "label56";
			this.label56.Size = new Size(77, 12);
			this.label56.TabIndex = 88;
			this.label56.Text = "越限恢复系数";
			this.label57.AutoSize = true;
			this.label57.Location = new Point(387, 19);
			this.label57.Name = "label57";
			this.label57.Size = new Size(23, 12);
			this.label57.TabIndex = 87;
			this.label57.Text = "min";
			this.textBox29.Location = new Point(354, 16);
			this.textBox29.Name = "textBox29";
			this.textBox29.Size = new Size(27, 21);
			this.textBox29.TabIndex = 86;
			this.textBox29.Text = "0";
			this.label58.AutoSize = true;
			this.label58.Location = new Point(274, 19);
			this.label58.Name = "label58";
			this.label58.Size = new Size(77, 12);
			this.label58.TabIndex = 85;
			this.label58.Text = "越限持续时间";
			this.textBox30.Location = new Point(135, 16);
			this.textBox30.Name = "textBox30";
			this.textBox30.ReadOnly = true;
			this.textBox30.Size = new Size(102, 21);
			this.textBox30.TabIndex = 83;
			this.textBox30.Text = "0000";
			this.label60.AutoSize = true;
			this.label60.Location = new Point(16, 19);
			this.label60.Name = "label60";
			this.label60.Size = new Size(113, 12);
			this.label60.TabIndex = 82;
			this.label60.Text = "三相电流不平衡限值";
			this.label61.AutoSize = true;
			this.label61.Location = new Point(249, 486);
			this.label61.Name = "label61";
			this.label61.Size = new Size(23, 12);
			this.label61.TabIndex = 95;
			this.label61.Text = "min";
			this.textBox31.Location = new Point(127, 483);
			this.textBox31.Name = "textBox31";
			this.textBox31.Size = new Size(121, 21);
			this.textBox31.TabIndex = 94;
			this.textBox31.Text = "0";
			this.label62.AutoSize = true;
			this.label62.Location = new Point(20, 486);
			this.label62.Name = "label62";
			this.label62.Size = new Size(101, 12);
			this.label62.TabIndex = 93;
			this.label62.Text = "连续失压时间限值";
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			
			base.ClientSize = new Size(612, 517);
			base.Controls.Add(this.label61);
			base.Controls.Add(this.textBox31);
			base.Controls.Add(this.label62);
			base.Controls.Add(this.groupBox10);
			base.Controls.Add(this.groupBox9);
			base.Controls.Add(this.groupBox8);
			base.Controls.Add(this.groupBox7);
			base.Controls.Add(this.groupBox4);
			base.Controls.Add(this.groupBox6);
			base.Controls.Add(this.groupBox5);
			base.Controls.Add(this.groupBox3);
			base.Controls.Add(this.groupBox2);
			base.Controls.Add(this.groupBox1);
			base.Name = "AFN04_26";
			this.Text = "测量点限值参数";
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			this.groupBox3.ResumeLayout(false);
			this.groupBox3.PerformLayout();
			this.groupBox5.ResumeLayout(false);
			this.groupBox5.PerformLayout();
			this.groupBox6.ResumeLayout(false);
			this.groupBox6.PerformLayout();
			this.groupBox4.ResumeLayout(false);
			this.groupBox4.PerformLayout();
			this.groupBox7.ResumeLayout(false);
			this.groupBox7.PerformLayout();
			this.groupBox8.ResumeLayout(false);
			this.groupBox8.PerformLayout();
			this.groupBox9.ResumeLayout(false);
			this.groupBox9.PerformLayout();
			this.groupBox10.ResumeLayout(false);
			this.groupBox10.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}
	}
}
