using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
namespace GB698Cls
{
	public class AFN04_27 : iForm
	{
		private IContainer components = null;
		private Label label24;
		private TextBox textBox12;
		private Label label23;
		private Label label22;
		private TextBox textBox11;
		private Label label21;
		private Label label20;
		private TextBox textBox10;
		private Label label19;
		private Label label18;
		private TextBox textBox9;
		private Label label17;
		private Label label16;
		private TextBox textBox8;
		private Label label15;
		private Label label14;
		private TextBox textBox7;
		private Label label13;
		private Label label12;
		private TextBox textBox6;
		private Label label11;
		private Label label10;
		private TextBox textBox4;
		private Label label9;
		private Label label8;
		private TextBox textBox3;
		private Label label7;
		private Label label6;
		private TextBox textBox2;
		private Label label5;
		private Label label2;
		private TextBox textBox1;
		private Label label1;
		private Label label4;
		private Label label3;
		private TextBox textBox5;
		public AFN04_27()
		{
			this.InitializeComponent();
			base.HelpButton = true;
		}
		protected override void GetText()
		{
			this.Data = "";
			string text = string.Empty;
			text += base.OperaSend(this.textBox5.Text, 2, "A26");
			text += base.OperaSend(this.textBox1.Text, 2, "A26");
			text += base.OperaSend(this.textBox2.Text, 2, "A26");
			text += base.OperaSend(this.textBox3.Text, 2, "A26");
			text += base.OperaSend(this.textBox8.Text, 2, "A26");
			text += base.OperaSend(this.textBox7.Text, 2, "A26");
			text += base.OperaSend(this.textBox6.Text, 2, "A26");
			text += base.OperaSend(this.textBox4.Text, 2, "A26");
			text += base.OperaSend(this.textBox12.Text, 2, "A26");
			text += base.OperaSend(this.textBox11.Text, 2, "A26");
			text += base.OperaSend(this.textBox10.Text, 2, "A26");
			text += base.OperaSend(this.textBox9.Text, 2, "A26");
			this.Data = text;
		}
		public override void SetText()
		{
			checked
			{
				if (!string.IsNullOrEmpty(this.Data))
				{
					string data = this.Data;
					int num = 0;
					this.textBox5.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox1.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox2.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox3.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox8.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox7.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox6.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox4.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox12.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox11.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox10.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
					this.textBox9.Text = base.OperaRec(data.Substring(num, 4), "A26");
					num += 4;
				}
			}
		}
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (this.components != null)
				{
					this.components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.textBox5 = new TextBox();
			this.label3 = new Label();
			this.label4 = new Label();
			this.label1 = new Label();
			this.textBox1 = new TextBox();
			this.label2 = new Label();
			this.label5 = new Label();
			this.textBox2 = new TextBox();
			this.label6 = new Label();
			this.label7 = new Label();
			this.textBox3 = new TextBox();
			this.label8 = new Label();
			this.label9 = new Label();
			this.textBox4 = new TextBox();
			this.label10 = new Label();
			this.label11 = new Label();
			this.textBox6 = new TextBox();
			this.label12 = new Label();
			this.label13 = new Label();
			this.textBox7 = new TextBox();
			this.label14 = new Label();
			this.label15 = new Label();
			this.textBox8 = new TextBox();
			this.label16 = new Label();
			this.label17 = new Label();
			this.textBox9 = new TextBox();
			this.label18 = new Label();
			this.label19 = new Label();
			this.textBox10 = new TextBox();
			this.label20 = new Label();
			this.label21 = new Label();
			this.textBox11 = new TextBox();
			this.label22 = new Label();
			this.label23 = new Label();
			this.textBox12 = new TextBox();
			this.label24 = new Label();
			base.SuspendLayout();
			this.textBox5.Location = new Point(92, 16);
			this.textBox5.Name = "textBox5";
			this.textBox5.Size = new Size(75, 21);
			this.textBox5.TabIndex = 26;
			this.textBox5.Text = "0";
			this.label3.AutoSize = true;
			this.label3.Location = new Point(28, 19);
			this.label3.Name = "label3";
			this.label3.Size = new Size(59, 12);
			this.label3.TabIndex = 25;
			this.label3.Text = "A相电阻RA";
			this.label4.AutoSize = true;
			this.label4.Location = new Point(170, 19);
			this.label4.Name = "label4";
			this.label4.Size = new Size(17, 12);
			this.label4.TabIndex = 39;
			this.label4.Text = "Ω";
			this.label1.AutoSize = true;
			this.label1.Location = new Point(170, 46);
			this.label1.Name = "label1";
			this.label1.Size = new Size(17, 12);
			this.label1.TabIndex = 42;
			this.label1.Text = "Ω";
			this.textBox1.Location = new Point(92, 43);
			this.textBox1.Name = "textBox1";
			this.textBox1.Size = new Size(75, 21);
			this.textBox1.TabIndex = 41;
			this.textBox1.Text = "0";
			this.label2.AutoSize = true;
			this.label2.Location = new Point(28, 46);
			this.label2.Name = "label2";
			this.label2.Size = new Size(59, 12);
			this.label2.TabIndex = 40;
			this.label2.Text = "A相电抗XA";
			this.label5.AutoSize = true;
			this.label5.Location = new Point(349, 20);
			this.label5.Name = "label5";
			this.label5.Size = new Size(11, 12);
			this.label5.TabIndex = 45;
			this.label5.Text = "S";
			this.textBox2.Location = new Point(271, 16);
			this.textBox2.Name = "textBox2";
			this.textBox2.Size = new Size(75, 21);
			this.textBox2.TabIndex = 44;
			this.textBox2.Text = "0";
			this.label6.AutoSize = true;
			this.label6.Location = new Point(207, 19);
			this.label6.Name = "label6";
			this.label6.Size = new Size(59, 12);
			this.label6.TabIndex = 43;
			this.label6.Text = "A相电导GA";
			this.label7.AutoSize = true;
			this.label7.Location = new Point(349, 47);
			this.label7.Name = "label7";
			this.label7.Size = new Size(11, 12);
			this.label7.TabIndex = 48;
			this.label7.Text = "S";
			this.textBox3.Location = new Point(271, 43);
			this.textBox3.Name = "textBox3";
			this.textBox3.Size = new Size(75, 21);
			this.textBox3.TabIndex = 47;
			this.textBox3.Text = "0";
			this.label8.AutoSize = true;
			this.label8.Location = new Point(207, 46);
			this.label8.Name = "label8";
			this.label8.Size = new Size(59, 12);
			this.label8.TabIndex = 46;
			this.label8.Text = "A相电纳BA";
			this.label9.AutoSize = true;
			this.label9.Location = new Point(349, 115);
			this.label9.Name = "label9";
			this.label9.Size = new Size(11, 12);
			this.label9.TabIndex = 60;
			this.label9.Text = "S";
			this.textBox4.Location = new Point(271, 111);
			this.textBox4.Name = "textBox4";
			this.textBox4.Size = new Size(75, 21);
			this.textBox4.TabIndex = 59;
			this.textBox4.Text = "0";
			this.label10.AutoSize = true;
			this.label10.Location = new Point(207, 114);
			this.label10.Name = "label10";
			this.label10.Size = new Size(59, 12);
			this.label10.TabIndex = 58;
			this.label10.Text = "B相电纳BA";
			this.label11.AutoSize = true;
			this.label11.Location = new Point(349, 88);
			this.label11.Name = "label11";
			this.label11.Size = new Size(11, 12);
			this.label11.TabIndex = 57;
			this.label11.Text = "S";
			this.textBox6.Location = new Point(271, 84);
			this.textBox6.Name = "textBox6";
			this.textBox6.Size = new Size(75, 21);
			this.textBox6.TabIndex = 56;
			this.textBox6.Text = "0";
			this.label12.AutoSize = true;
			this.label12.Location = new Point(207, 87);
			this.label12.Name = "label12";
			this.label12.Size = new Size(59, 12);
			this.label12.TabIndex = 55;
			this.label12.Text = "B相电导GA";
			this.label13.AutoSize = true;
			this.label13.Location = new Point(170, 114);
			this.label13.Name = "label13";
			this.label13.Size = new Size(17, 12);
			this.label13.TabIndex = 54;
			this.label13.Text = "Ω";
			this.textBox7.Location = new Point(92, 111);
			this.textBox7.Name = "textBox7";
			this.textBox7.Size = new Size(75, 21);
			this.textBox7.TabIndex = 53;
			this.textBox7.Text = "0";
			this.label14.AutoSize = true;
			this.label14.Location = new Point(28, 114);
			this.label14.Name = "label14";
			this.label14.Size = new Size(59, 12);
			this.label14.TabIndex = 52;
			this.label14.Text = "B相电抗XA";
			this.label15.AutoSize = true;
			this.label15.Location = new Point(170, 87);
			this.label15.Name = "label15";
			this.label15.Size = new Size(17, 12);
			this.label15.TabIndex = 51;
			this.label15.Text = "Ω";
			this.textBox8.Location = new Point(92, 84);
			this.textBox8.Name = "textBox8";
			this.textBox8.Size = new Size(75, 21);
			this.textBox8.TabIndex = 50;
			this.textBox8.Text = "0";
			this.label16.AutoSize = true;
			this.label16.Location = new Point(28, 87);
			this.label16.Name = "label16";
			this.label16.Size = new Size(59, 12);
			this.label16.TabIndex = 49;
			this.label16.Text = "B相电阻RA";
			this.label17.AutoSize = true;
			this.label17.Location = new Point(349, 181);
			this.label17.Name = "label17";
			this.label17.Size = new Size(11, 12);
			this.label17.TabIndex = 72;
			this.label17.Text = "S";
			this.textBox9.Location = new Point(271, 177);
			this.textBox9.Name = "textBox9";
			this.textBox9.Size = new Size(75, 21);
			this.textBox9.TabIndex = 71;
			this.textBox9.Text = "0";
			this.label18.AutoSize = true;
			this.label18.Location = new Point(207, 180);
			this.label18.Name = "label18";
			this.label18.Size = new Size(59, 12);
			this.label18.TabIndex = 70;
			this.label18.Text = "C相电纳BA";
			this.label19.AutoSize = true;
			this.label19.Location = new Point(349, 154);
			this.label19.Name = "label19";
			this.label19.Size = new Size(11, 12);
			this.label19.TabIndex = 69;
			this.label19.Text = "S";
			this.textBox10.Location = new Point(271, 150);
			this.textBox10.Name = "textBox10";
			this.textBox10.Size = new Size(75, 21);
			this.textBox10.TabIndex = 68;
			this.textBox10.Text = "0";
			this.label20.AutoSize = true;
			this.label20.Location = new Point(207, 153);
			this.label20.Name = "label20";
			this.label20.Size = new Size(59, 12);
			this.label20.TabIndex = 67;
			this.label20.Text = "C相电导GA";
			this.label21.AutoSize = true;
			this.label21.Location = new Point(170, 180);
			this.label21.Name = "label21";
			this.label21.Size = new Size(17, 12);
			this.label21.TabIndex = 66;
			this.label21.Text = "Ω";
			this.textBox11.Location = new Point(92, 177);
			this.textBox11.Name = "textBox11";
			this.textBox11.Size = new Size(75, 21);
			this.textBox11.TabIndex = 65;
			this.textBox11.Text = "0";
			this.label22.AutoSize = true;
			this.label22.Location = new Point(28, 180);
			this.label22.Name = "label22";
			this.label22.Size = new Size(59, 12);
			this.label22.TabIndex = 64;
			this.label22.Text = "C相电抗XA";
			this.label23.AutoSize = true;
			this.label23.Location = new Point(170, 153);
			this.label23.Name = "label23";
			this.label23.Size = new Size(17, 12);
			this.label23.TabIndex = 63;
			this.label23.Text = "Ω";
			this.textBox12.Location = new Point(92, 150);
			this.textBox12.Name = "textBox12";
			this.textBox12.Size = new Size(75, 21);
			this.textBox12.TabIndex = 62;
			this.textBox12.Text = "0";
			this.label24.AutoSize = true;
			this.label24.Location = new Point(28, 153);
			this.label24.Name = "label24";
			this.label24.Size = new Size(59, 12);
			this.label24.TabIndex = 61;
			this.label24.Text = "C相电阻RA";
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			
			base.ClientSize = new Size(384, 218);
			base.Controls.Add(this.label17);
			base.Controls.Add(this.textBox9);
			base.Controls.Add(this.label18);
			base.Controls.Add(this.label19);
			base.Controls.Add(this.textBox10);
			base.Controls.Add(this.label20);
			base.Controls.Add(this.label21);
			base.Controls.Add(this.textBox11);
			base.Controls.Add(this.label22);
			base.Controls.Add(this.label23);
			base.Controls.Add(this.textBox12);
			base.Controls.Add(this.label24);
			base.Controls.Add(this.label9);
			base.Controls.Add(this.textBox4);
			base.Controls.Add(this.label10);
			base.Controls.Add(this.label11);
			base.Controls.Add(this.textBox6);
			base.Controls.Add(this.label12);
			base.Controls.Add(this.label13);
			base.Controls.Add(this.textBox7);
			base.Controls.Add(this.label14);
			base.Controls.Add(this.label15);
			base.Controls.Add(this.textBox8);
			base.Controls.Add(this.label16);
			base.Controls.Add(this.label7);
			base.Controls.Add(this.textBox3);
			base.Controls.Add(this.label8);
			base.Controls.Add(this.label5);
			base.Controls.Add(this.textBox2);
			base.Controls.Add(this.label6);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.textBox1);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.label4);
			base.Controls.Add(this.textBox5);
			base.Controls.Add(this.label3);
			base.Name = "AFN04_27";
			this.Text = "测量点铜损、铁损参数";
			base.ResumeLayout(false);
			base.PerformLayout();
		}
	}
}
