//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TTT.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TTT_FORM                    101
#define IDR_MAINFRAME                   128
#define IDR_TTTTYPE                     129
#define IDD_DIALOG_SET                  131
#define IDD_FORMVIEW_REALWAVE           141
#define IDD_DIALOG_ANGLESET             142
#define IDD_DIALOG_SWITCHLINE           143
#define IDB_WIN2500                     145
#define IDD_CARDDIALOG                  146
#define IDD_DATACHULI                   150
#define IDD_CHANGEDIALOG                151
#define IDD_TIMEEVERY                   152
#define IDD_DIALOGTIME                  153
#define IDD_PARAMETERSET                206
#define IDD_PARAMETERSET1               207
#define IDD_TTT_FORM1                   208
#define IDD_TTT_FORM2                   209
#define IDC_WAVE                        1000
#define IDC_BUTTON_START                1001
#define IDC_BUTTON_STOP                 1002
#define IDC_REAL_START                  1003
#define IDC_BUTTON_SET                  1004
#define IDC_REAL_RECORD                 1004
#define IDC_COMBO1                      1005
#define IDC_COMBO_CHNNUM                1005
#define IDC_COMBO_CYCLENUM              1005
#define IDC_COMBO_SWITCHLINE            1005
#define IDC_CARDCOMBO                   1005
#define IDC_COMBO_CHNUM                 1006
#define IDC_REAL_SEND                   1006
#define IDC_SETTIMER                    1007
#define IDC_BUTTON_TESTPHASE            1008
#define IDC_EDIT_SMPRATE                1012
#define IDC_SPIN_SMPRATE                1013
#define IDC_COMBO_SMPRATE               1014
#define IDC_CHECK_CH0                   1015
#define IDC_CHECK_CH3                   1016
#define IDC_CHECK_CH1                   1017
#define IDC_CHECK_CH4                   1018
#define IDC_CHECK_CH2                   1019
#define IDC_CHECK_CH5                   1020
#define IDC_ANALYZE                     1022
#define IDC_BUTTON_STARTREC             1023
#define IDC_DANGLE                      1023
#define IDC_BUTTON_STOPREC              1024
#define IDC_BUTTON_UPDATE               1025
#define IDC_EDIT_GAIN                   1028
#define IDC_EDIT_STARTPOINT             1029
#define IDC_EDIT_EXTEND                 1031
#define IDC_RADIO_REALTIME              1032
#define IDC_RADIO_ANALYZE               1033
#define IDC_BUTTON_SHIFTLEFT            1034
#define IDC_BUTTON_ASHIFTLEFT           1035
#define IDC_BUTTON_SHIFTRIGHT           1036
#define IDC_BUTTON_ASHIFTRIGHT          1037
#define IDC_EDIT_GAINSMPWIN             1038
#define IDC_CHECK1                      1039
#define IDC_ALLADD                      1039
#define IDC_CHECK2                      1040
#define IDC_CHECK_DVDT                  1040
#define IDC_ANGLESET                    1040
#define IDC_FINDPIPEVALUE               1040
#define IDC_CHECK3                      1041
#define IDC_CHECK_AVER4                 1041
#define IDC_DANGLESET                   1041
#define IDC_CHECK4                      1042
#define IDC_CHECK_DIFFI                 1042
#define IDC_READANGLE                   1042
#define IDC_CHECK5                      1043
#define IDC_ANGLESETB                   1043
#define IDC_CHECK6                      1044
#define IDC_READANGLEB                  1044
#define IDC_CHECK_ALLDIFF               1044
#define IDC_RADIO_ANALYZE2              1044
#define IDC_COMSET                      1044
#define IDC_CHECK7                      1045
#define IDC_ANGLESETC                   1045
#define IDC_CHECK8                      1046
#define IDC_READANGLEC                  1046
#define IDC_ADDONE                      1046
#define IDC_STATIC_DISPSCALEP           1047
#define IDC_READANGLECD                 1047
#define IDC_STATIC_DISPSCALEN           1048
#define IDC_STATIC_ANALYZESCALEP        1049
#define IDC_STATIC_ANALYZESCALEN        1050
#define IDC_COMBO_CHSELECT              1051
#define IDC_RADIO_REC                   1052
#define IDC_CHECK9                      1052
#define IDC_RADIO_ANA                   1053
#define IDC_SIX                         1053
#define IDC_EDIT_CURRENTGAINSMPWIN      1053
#define IDC_BUTTON_LOAD                 1054
#define IDC_CHECK_DIFFI2                1055
#define IDC_ZHONGZHI                    1056
#define IDC_BUTTON_SAVE                 1057
#define IDC_CHECK_PARITY                1058
#define IDC_FFT                         1058
#define IDC_EDIT_CODEWIN                1059
#define IDC_CHECK_DIFFI3                1059
#define IDC_BUTTON_DECODE               1060
#define IDC_EDIT_CODEWIN1               1061
#define IDC_BUTTON_TEST                 1062
#define IDC_EDIT_ANGLE                  1063
#define IDC_BUTTON_ANGLESET             1064
#define IDC_EDIT_PASSWORD               1065
#define IDC_EDIT_SENDCODE               1066
#define IDC_BUTTON_SEND                 1067
#define IDC_EDIT_THRESHOLD              1068
#define IDC_EDIT_MINSUM                 1069
#define IDC_BUTTON_SWITCHLINE           1070
#define IDC_EDIT_CODEWIN2               1071
#define IDC_BUTTON_ANGLE                1071
#define IDC_CHECK_CH8                   1072
#define IDC_CHECK_CH9                   1073
#define IDC_CHECK_CH10                  1074
#define IDC_EDIT_BANDPASSANGLE          1075
#define IDC_BUTTON_BANDPASSANGLESET     1076
#define IDC_GENERATRIXNO                1077
#define IDC_SPIN                        1078
#define IDC_DATAVALUE                   1079
#define IDC_REALSTOP                    1081
#define IDC_GENERATRIX                  1082
#define IDC_LINE                        1083
#define IDC_DECODE                      1083
#define IDC_STARTREADING                1084
#define IDC_SENDALLONE                  1084
#define IDC_SPIN2                       1085
#define IDC_PHASE                       1086
#define IDC_SPIN3                       1087
#define IDC_MODULE                      1088
#define IDC_SPIN4                       1089
#define IDC_ORDER                       1090
#define IDC_STARTPOINT                  1092
#define IDC_WAVEPOINTS                  1093
#define IDC_READLINE                    1094
#define IDC_SENDORDER                   1095
#define IDC_RECEIVE                     1096
#define IDC_PROTOCOLS                   1097
#define IDC_SEND                        1098
#define IDC_CHECK10                     1101
#define IDC_READFILTER                  1104
#define IDC_DELETEFILE                  1106
#define IDC_OPENFILE                    1107
#define IDC_RADIO1                      1108
#define IDC_RADIO2                      1109
#define IDC_STATICFILE                  1110
#define IDC_RADIO4                      1110
#define IDC_STATICFILE2                 1111
#define IDC_RADIO5                      1111
#define IDC_RADIO3                      1112
#define IDC_BCHTEST                     1113
#define IDC_RADIO6                      1114
#define IDC_STATIC1                     1120
#define IDC_STATIC2                     1121
#define IDC_STATIC3                     1122
#define IDC_CHECK11                     1124
#define IDC_DFA                         1125
#define IDC_DFB                         1126
#define IDC_X0                          1127
#define IDC_X1                          1128
#define IDC_TESTDATA                    1128
#define IDC_SPINSTART                   1129
#define IDC_SPINAVERAGE                 1130
#define IDC_FINDZERO                    1131
#define IDC_ALLTIMES                    1132
#define IDC_COMBOPORT                   1133
#define IDC_COMBOBIT                    1134
#define IDC_CHECKCOMBOX                 1135
#define IDC_DATACOMBO                   1136
#define IDC_STOPCOMBO                   1137
#define IDC_INITIALIZE                  1138
#define IDC_DELAY                       1139
#define IDC_MSCOMM                      1140
#define IDC_STATIC50                    1141
#define IDC_STATIC51                    1142
#define IDC_STATIC52                    1143
#define IDC_STATIC53                    1144
#define IDC_STATIC54                    1145
#define IDC_SANGLE                      1146
#define IDC_STATIC55                    1146
#define IDC_SANGLEB                     1147
#define IDC_STATIC56                    1147
#define IDC_SANGLEC                     1148
#define IDC_ANGLE                       1149
#define IDC_STATIC57                    1150
#define IDC_EDITT                       1151
#define IDC_CHECK4BIT                   1152
#define IDC_CHECK12                     1153
#define IDC_IS0STATION                  1154
#define IDC_CHANGEUSEDATA               1155
#define ID_CLOSE                        1156
#define IDC_SOURCEFILE                  1157
#define IDC_DESTFILE                    1158
#define IDC_CHANGE                      1159
#define IDC_XISHU                       1160
#define IDC_SOURCESTATIC                1161
#define IDC_DESTSTATIC                  1162
#define IDC_SECONDS                     1163
#define IDC_EDITTIME                    1164
#define IDC_CHECK13                     1166
#define IDC_ORDERCOMBO                  1167
#define IDC_DELAYHAOMIAO                1168
#define IDC_BUTTON1                     1169
#define IDM_WAVE_REAL                   32771
#define IDM_WAVE_ANALYZE                32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
