// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_rdoColumn wrapper class

class C_rdoColumn : public COleDispatchDriver
{
public:
	C_rdoColumn() {}		// Calls COleDispatchDriver default constructor
	C_rdoColumn(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	C_rdoColumn(const C_rdoColumn& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetValue();
	void SetValue(const VARIANT& newValue);
	long GetType();
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	BOOL GetAllowZeroLength();
	void SetAllowZeroLength(BOOL bNewValue);
	long GetAttributes();
	BOOL GetUpdatable();
	void SetUpdatable(BOOL bNewValue);
	short GetOrdinalPosition();
	BOOL GetRequired();
	CString GetSourceColumn();
	void SetSourceColumn(LPCTSTR lpszNewValue);
	CString GetSourceTable();
	void SetSourceTable(LPCTSTR lpszNewValue);
	BOOL GetChunkRequired();
	void AppendChunk(const VARIANT& Chunk);
	VARIANT GetChunk(long Size);
	long ColumnSize();
	VARIANT GetBatchConflictValue();
	VARIANT GetOriginalValue();
	long GetStatus();
	void SetStatus(long nNewValue);
	BOOL GetKeyColumn();
	void SetKeyColumn(BOOL bNewValue);
};
