// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rdoconnections.h"

// Dispatch interfaces referenced by this interface
#include "_rdoconnection.h"


/////////////////////////////////////////////////////////////////////////////
// CrdoConnections properties

/////////////////////////////////////////////////////////////////////////////
// CrdoConnections operations

long CrdoConnections::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CrdoConnections::Remove(const VARIANT& ItemToRemove)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ItemToRemove);
}

void CrdoConnections::Add(LPDISPATCH prdoConnection)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 prdoConnection);
}

C_rdoConnection CrdoConnections::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return C_rdoConnection(pDispatch);
}
