// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_rdoColumn;

/////////////////////////////////////////////////////////////////////////////
// CrdoColumns wrapper class

class CrdoColumns : public COleDispatchDriver
{
public:
	CrdoColumns() {}		// Calls COleDispatchDriver default constructor
	CrdoColumns(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoColumns(const CrdoColumns& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Refresh();
	C_rdoColumn GetItem(const VARIANT& Index);
};
