// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_rdoEnvironment;

/////////////////////////////////////////////////////////////////////////////
// CrdoEnvironments wrapper class

class CrdoEnvironments : public COleDispatchDriver
{
public:
	CrdoEnvironments() {}		// Calls COleDispatchDriver default constructor
	CrdoEnvironments(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoEnvironments(const CrdoEnvironments& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Remove(const VARIANT& ItemToRemove);
	void Add(LPDISPATCH prdoEnvironment);
	C_rdoEnvironment GetItem(const VARIANT& Index);
};
