// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rdoenvironments.h"

// Dispatch interfaces referenced by this interface
#include "_rdoenvironment.h"


/////////////////////////////////////////////////////////////////////////////
// CrdoEnvironments properties

/////////////////////////////////////////////////////////////////////////////
// CrdoEnvironments operations

long CrdoEnvironments::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CrdoEnvironments::Remove(const VARIANT& ItemToRemove)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ItemToRemove);
}

void CrdoEnvironments::Add(LPDISPATCH prdoEnvironment)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 prdoEnvironment);
}

C_rdoEnvironment CrdoEnvironments::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return C_rdoEnvironment(pDispatch);
}
