// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoPreparedStatement;

/////////////////////////////////////////////////////////////////////////////
// CrdoPreparedStatements wrapper class

class CrdoPreparedStatements : public COleDispatchDriver
{
public:
	CrdoPreparedStatements() {}		// Calls COleDispatchDriver default constructor
	CrdoPreparedStatements(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoPreparedStatements(const CrdoPreparedStatements& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
