// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rdoparameters.h"

// Dispatch interfaces referenced by this interface
#include "rdoparameter.h"


/////////////////////////////////////////////////////////////////////////////
// CrdoParameters properties

/////////////////////////////////////////////////////////////////////////////
// CrdoParameters operations

long CrdoParameters::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CrdoParameter CrdoParameters::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return CrdoParameter(pDispatch);
}
