// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CrdoParameter wrapper class

class CrdoParameter : public COleDispatchDriver
{
public:
	CrdoParameter() {}		// Calls COleDispatchDriver default constructor
	CrdoParameter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoParameter(const CrdoParameter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	long GetType();
	void SetType(long nNewValue);
	VARIANT GetValue();
	void SetValue(const VARIANT& newValue);
	long GetDirection();
	void SetDirection(long nNewValue);
	void AppendChunk(const VARIANT& Chunk);
	long GetSize();
	void SetSize(long nNewValue);
};
