// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoParameter;

/////////////////////////////////////////////////////////////////////////////
// CrdoParameters wrapper class

class CrdoParameters : public COleDispatchDriver
{
public:
	CrdoParameters() {}		// Calls COleDispatchDriver default constructor
	CrdoParameters(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoParameters(const CrdoParameters& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CrdoParameter GetItem(const VARIANT& Index);
};
