// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rdoqueries.h"

// Dispatch interfaces referenced by this interface
#include "rdopreparedstatement.h"


/////////////////////////////////////////////////////////////////////////////
// CrdoQueries properties

/////////////////////////////////////////////////////////////////////////////
// CrdoQueries operations

long CrdoQueries::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CrdoPreparedStatement CrdoQueries::GetItem(const VARIANT& Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&Index);
	return CrdoPreparedStatement(pDispatch);
}
