// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class C_rdoResultset;

/////////////////////////////////////////////////////////////////////////////
// CrdoResultsets wrapper class

class CrdoResultsets : public COleDispatchDriver
{
public:
	CrdoResultsets() {}		// Calls COleDispatchDriver default constructor
	CrdoResultsets(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoResultsets(const CrdoResultsets& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	C_rdoResultset GetItem(const VARIANT& Index);
};
