// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoColumns;
class C_rdoResultset;

/////////////////////////////////////////////////////////////////////////////
// CrdoTable wrapper class

class CrdoTable : public COleDispatchDriver
{
public:
	CrdoTable() {}		// Calls COleDispatchDriver default constructor
	CrdoTable(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoTable(const CrdoTable& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CrdoColumns GetRdoColumns();
	CString GetName();
	BOOL GetUpdatable();
	long GetRowCount();
	CString GetType();
	C_rdoResultset OpenResultset(const VARIANT& Type, const VARIANT& LockType, const VARIANT& Options);
};
