// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CrdoTable;

/////////////////////////////////////////////////////////////////////////////
// CrdoTables wrapper class

class CrdoTables : public COleDispatchDriver
{
public:
	CrdoTables() {}		// Calls COleDispatchDriver default constructor
	CrdoTables(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CrdoTables(const CrdoTables& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void Refresh();
	CrdoTable GetItem(const VARIANT& Index);
};
