//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IFRM.rc
//
#define ID_SSETMOTHER                   2
#define ID_DELETE                       3
#define ID_ADD_RECORD                   3
#define ID_SAVEDATA                     3
#define ID_UNDO                         3
#define ID_PASSOUT                      3
#define ID_DISCONNECT                   3
#define ID_HIGHSET                      3
#define ID_ALLSELECT                    3
#define ID_SETLINE                      3
#define IDR_SRVR_INPLACE                4
#define ID_REPLACE                      4
#define ID_CLEAR                        4
#define ID_LINEDEAL                     4
#define ID_ALLABANDON                   4
#define ID_CANCEL                       4
#define IDR_SRVR_EMBEDDED               5
#define ID_WRITETOTEXTFILE              5
#define IDC_SEARCHMODUKE                5
#define ID_FINDNOREADMODULE             5
#define IDR_CNTR_INPLACE                6
#define ID_WRITETOEXCELFILE             6
#define ID_GETFROM                      7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_IFRM_FORM                   101
#define ID_INDICATOR_PROGRESS_PANE      101
#define IDP_FAILED_TO_CREATE            102
#define AFX_REPORT_TITLE                103
#define IDP_SOCKETS_INIT_FAILED         104
#define CG_IDD_MYDIALOGBAR              105
#define ID_PROGRESSDLGTITLE             105
#define CG_ID_VIEW_MYDIALOGBAR          106
#define CG_IDD_PROGRESS                 107
#define ID_APPEARDINGSHI                107
#define CG_IDS_PROGRESS_CAPTION         108
#define ID_ANIMATE                      108
#define ID_PROGRESSDLGUPDATE            109
#define CG_IDD_MYDIALOGDATA             110
#define CG_ID_VIEW_MYDIALOGDATA         111
#define IDR_MAINFRAME                   128
#define IDR_LONGDISTANCEMENU            128
#define IDR_TURTLETYPE                  129
#define IDB_BITMAP_STATE2               129
#define IDR_MAINFRAME10                 129
#define IDB_BITMAP_STATE                130
#define IDD_DATE_SELECT                 130
#define IDR_MAINFRAME1                  131
#define IDR_MAINFRAME3                  131
#define IDD_DISPLAY                     132
#define IDR_MAINFRAME4                  132
#define IDR_MAINFRAME5                  133
#define IDR_MAINFRAME6                  134
#define IDR_AVITEST                     134
#define IDI_LINE2                       135
#define IDR_MAINFRAMEBAK                135
#define IDR_MAINFRAME2                  136
#define IDR_VICINITITYMENU              136
#define IDR_LONGDISTANCEMENU1           137
#define IDR_MAINFRAME6406               137
#define IDR_VICINITITYMENU1             138
#define IDR_MAINFRAME11                 138
#define IDI_SUB2                        139
#define IDI_SUB                         139
#define IDR_MAINFRAME12                 139
#define IDR_MAINFRAMENEW                140
#define IDI_DEVICES                     141
#define IDI_BIGMODULES                  141
#define IDI_BIGMODULE                   141
#define IDI_COMPANY                     142
#define IDI_TRANS                       143
#define IDI_MODULES                     144
#define IDI_MODULE                      144
#define IDD_START                       145
#define IDI_TOLMODULES                  145
#define IDB_HELP_DISABLE                147
#define IDI_SUBMODULES                  147
#define IDI_SUBSALEMODULE               147
#define IDB_HELP_FOCUS                  148
#define IDI_LINEMODULE                  148
#define IDI_LSALEMODULE                 148
#define IDB_HELP_DOWN                   150
#define IDB_EXIT_DOWN                   152
#define IDB_EXIT_FOCUS                  153
#define IDB_EXIT_DISABLE                154
#define IDB_BACKGROUND                  156
#define IDB_REFRESH_DISABLE             157
#define IDB_OPERATE_FOCUS               158
#define IDB_OPERATE_DISABLE             159
#define IDB_REFRESH_DOWN                160
#define IDB_REFRESH_FOCUS               161
#define IDB_OPERATE_DOWN                162
#define IDD_AMMETTER                    164
#define IDD_TRANSFORMER                 165
#define IDD_USERINFO                    166
#define IDD_BREADSETTING                167
#define IDD_READSETTING                 168
#define IDD_SEARCH                      169
#define IDD_REPORT                      171
#define IDB_SUBSTATION_DISABLE          172
#define IDB_SUBSTATION_FOCUS            173
#define IDB_SUBSTATION_DOWN             174
#define IDB_AMMETER_DISABLE             175
#define IDB_AMMETER_FOCUS               176
#define IDB_AMMETER_DOWN                177
#define IDB_USERINFO_DISABLE            178
#define IDB_USERINFO_FOCUS              179
#define IDB_USERINFO_DOWN               180
#define IDB_DATA_DISABLE                181
#define IDB_DATA_FOCUS                  182
#define IDB_DATA_DOWN                   183
#define IDD_COMMUNICATION               184
#define IDD_LINELOSS                    186
#define IDD_DATAINFO                    187
#define IDD_LINELOSS3                   188
#define IDB_LINES                       192
#define IDD_PASSWORD                    193
#define IDD_GARRISONINFO                194
#define IDD_CHARTDIALOG                 195
#define IDD_STATIONCOMM11               196
#define IDD_REPLDIALOG                  197
#define IDD_REPORTKIND                  198
#define IDD_PRICE                       200
#define IDD_BJDIALOG                    201
#define IDD_SELECTDATA                  202
#define IDD_TIMEDIALOG                  204
#define IDD_READTIMES                   205
#define IDD_PARAMETERSET                206
#define IDD_LINELOSS2                   207
#define IDD_CONDTION                    209
#define IDD_PHASETEST44                 212
#define IDD_DATAAPPEAR                  214
#define IDD_DATAAPPEAR1                 215
#define IDD_TRANSFORMER1                216
#define IDD_LINELOSS1                   217
#define IDD_LINELOSS4                   218
#define IDI_MODEM                       220
#define IDD_SELECTDIALOG                221
#define IDI_ANGLE                       222
#define IDI_PARAMETER                   223
#define IDI_TOTAL                       225
#define IDI_ELECT                       228
#define IDI_PASS                        229
#define IDI_HUMAN                       230
#define IDI_RUN                         232
#define IDI_PARAMETER1                  233
#define IDI_AMMETTER                    234
#define IDI_DATAAPPEAR                  234
#define IDI_POWER                       235
#define IDI_TRANSFORMER                 236
#define IDB_TRANSFORMER                 237
#define IDD_AUTOPARSET                  263
#define IDD_STATIONCOMM1                264
#define IDD_STATIONCOMM                 264
#define IDD_STATIONCOMM2                265
#define IDI_TIMER                       266
#define IDD_STATIONCOMM3                266
#define IDD_PARAMETERSET1               267
#define IDD_PARAMETERSET2               268
#define IDB_USETITLE                    269
#define IDD_USERINFO1                   269
#define IDB_TRANSFORMERTITLE            270
#define IDD_CONDTION1                   270
#define IDB_AMMETERTITLE                271
#define IDB_PRICETITLE                  272
#define IDB_WIN1500                     273
#define IDB_WIN3510                     273
#define IDB_WIN2500                     273
#define IDB_WIN4500                     274
#define IDB_WIN25001                    274
#define IDB_WIN3500                     275
#define IDB_ZHULIUTITLE                 276
#define IDB_ZSTITLE                     277
#define IDI_SQL                         279
#define IDB_COMPUTER                    281
#define IDI_LINEMODEM                   282
#define IDI_NETWORK                     283
#define IDI_KEY                         290
#define IDI_MODEM1                      291
#define IDI_LINE1                       293
#define IDI_LINE                        293
#define IDI_COMPANY1                    294
#define IDB_COMPANY                     297
#define IDB_BACKGROUND2                 298
#define IDB_AMKIND                      309
#define IDD_TIMECHECK                   310
#define IDD_APPEARSELECT                311
#define IDR_TYPE                        312
#define IDD_STATIONCOMM12               312
#define IDD_STATIONCOMM4                312
#define IDD_STATIONCOMM5                313
#define IDD_AUTOPARAMETER1              313
#define IDR_EYES                        314
#define IDD_SELECTDATA1                 314
#define IDD_PHASETEST1                  315
#define IDD_DATAAPPEAR2                 316
#define IDD_EVERYTIME                   317
#define IDI_MIS                         318
#define IDR_LIST_POPUP                  319
#define IDI_SALEMODULES                 319
#define IDI_ZSALEMODULE                 319
#define IDR_MAINFRAME8                  320
#define IDR_MAINFRAME9                  321
#define IDI_COMPANY2                    321
#define IDR_MAINFRAME7                  322
#define IDI_SUBq                        322
#define IDD_AUTOPARSETS                 323
#define IDI_TRANS1                      323
#define IDD_AUTOPARSETS1                324
#define IDI_SUB1                        324
#define IDD_AUTOPARAMETER2              325
#define IDD_SELECTDATA2                 326
#define IDD_PRICE1                      327
#define IDD_PRICE2                      328
#define IDD_IFRM_FORM1                  333
#define IDD_PASSWORD1                   334
#define IDB_FIND                        337
#define IDR_TREEMENU                    339
#define IDR_LOCALTREEMENU               339
#define IDR_REMOTETREEMENU              340
#define IDD_REMOTEDIALOG                341
#define IDR_REMOTEGREEMENU              341
#define IDI_FTP                         342
#define IDR_LONGDISTANCEMENU2           342
#define IDR_LOCALTREEMENU1              342
#define IDD_TELDIALOG                   343
#define IDI_TRANS2                      343
#define IDR_LONGDISTANCEMENU3           343
#define IDR_REMOTEGREEMENU1             343
#define IDD_CHILDSTATION                344
#define IDR_LONGDISTANCEMENU4           344
#define IDD_LINEDIALOG                  345
#define IDD_DIALOG2                     346
#define IDR_LONGDISTANCEMENU5           346
#define IDD_USERINFO3                   347
#define IDR_VICINITITYMENU3             347
#define IDD_INFODIALOG                  348
#define IDR_VICINITITYMENU2             348
#define IDD_AUTOPARAMETER3              349
#define IDR_VICINITITYMENU4             349
#define IDD_AUTOPARAMETER4              350
#define IDR_LONGDISTANCEMENU6           350
#define IDD_AUTOPARAMETER5              351
#define IDR_LONGDISTANCEMENU7           351
#define IDR_VICINITITYMENU5             351
#define IDD_DATE_SELECT1                352
#define IDR_LONGDISTANCEMENU8           352
#define IDR_VICINITITYMENU6             352
#define IDD_AUTOPARAMETERs              353
#define IDR_LONGDISTANCEMENU9           353
#define IDR_LOCALTREEMENU2              353
#define IDR_LONGDISTANCEMENU10          354
#define IDR_VICINITITYMENU7             354
#define IDR_VICINITITYMENU8             355
#define IDR_VICINITITYMENUold1          357
#define IDR_VICINITITYMENUNEW           358
#define IDR_RADAR                       364
#define IDI_DINGSHI                     368
#define IDI_DINGSHINULL                 369
#define IDD_AUTOPARAMETER               372
#define IDD_EVERYTIMES                  373
#define IDI_RESCYCLE                    373
#define IDD_USERINFO2                   374
#define IDD_PHASETEST2                  374
#define IDI_DINGCHECK                   374
#define IDD_DATAAPPEAR3                 375
#define IDD_PHASETEST3                  375
#define IDD_DATAAPPEAR4                 376
#define IDD_PHASETEST                   376
#define IDD_DATAAPPEAR5                 377
#define IDD_PASSWORD2                   378
#define IDB_BACKGROUND1                 380
#define IDB_DIALOGBARBACK               383
#define IDD_DATADIALOG                  386
#define IDD_PARAMETERSET3               387
#define CG_IDD_MYDIALOGBAR1             388
#define CG_IDD_MYDIALOGBAR2             389
#define IDD_PASSWORD3                   389
#define CG_IDD_MYDIALOGBAR3             390
#define IDB_LIST                        398
#define IDD_CONNECTSTATUS               408
#define IDI_CONNECT                     409
#define IDB_DISCONNECT                  411
#define IDB_CONNECT                     412
#define IDD_USERINFO4                   413
#define IDD_USERINFO5                   414
#define IDB_DOWNBUTTON                  414
#define IDD_SENDORSTOP                  416
#define CG_IDD_MYDIALOGBAR5             417
#define IDB_BITMAPDOWN                  419
#define IDD_USERINFO7                   419
#define IDB_BITMAPCLOSENORMAL           420
#define IDD_DATASHOW                    420
#define IDD_CONDTION2                   421
#define IDD_LINELOSS5                   422
#define IDD_LINELOSS6                   423
#define CG_IDD_MYDIALOGBAR4             424
#define IDD_PARAMETERSET4               425
#define IDD_PARAMETERSET5               426
#define IDD_PARAMETERSET6               427
#define IDB_SPLITE                      428
#define CG_IDD_MYDIALOGBAR6             428
#define CG_IDD_MYDIALOGBAR7             429
#define IDD_USERINFO6                   430
#define IDI_LISTDATA                    436
#define IDI_COMPENSATEMODULE            437
#define IDB_LINE                        438
#define IDI_SUBTOTALMODULE              438
#define IDB_HLINE                       439
#define IDI_ZTOLTALMODULE               439
#define IDD_PARAMETER                   440
#define IDI_LTOTALMODULE                440
#define IDI_ZSUBTOTALMODULE             441
#define IDB_USERTITLE                   443
#define CG_IDD_MYDIALOGBAR9             444
#define IDB_BMPBACK                     445
#define IDB_BACK                        446
#define CG_IDD_MYDIALOGBAR10            447
#define IDD_TIMESELECT                  450
#define IDD_MESSAGE                     453
#define CG_IDD_MYDIALOGBAR8             454
#define IDD_PARAMETERSET7               455
#define IDD_PHASETEST45                 456
#define IDD_PHASETEST4                  457
#define CG_IDD_MYDIALOGBAR12            459
#define IDD_AUTORRUN                    460
#define IDB_BACK2                       461
#define IDD_PARAMETERSET9               462
#define IDB_BACK3                       462
#define CG_IDD_MYDIALOGBAR16            466
#define CG_IDD_MYDIALOGBAR14            467
#define IDD_PARAMETERSET8               467
#define IDD_PARAMETERSET10              468
#define IDD_DIALOGCHECK                 468
#define CG_IDD_MYDIALOGBAR17            469
#define IDD_DATE_SELECT2                470
#define IDD_READRANGLE                  471
#define CG_IDD_MYDIALOGBAR11            473
#define CG_IDD_MYDIALOGBAR13            474
#define IDD_USERINFO8                   475
#define IDD_USERINFO10                  477
#define IDD_PARAMETERSET11              478
#define IDD_CHARTDIALOG1                479
#define IDD_PROTCOL                     479
#define CG_IDD_MYDIALOGBAR18            481
#define IDD_COMMSET                     481
#define CG_IDD_MYDIALOGBAR19            482
#define IDD_USERINFO9                   482
#define IDD_WUGONGDLG                   482
#define IDD_DATE_SELECT3                483
#define IDD_WUGONGSPACE                 483
#define IDD_CONDTION3                   484
#define IDD_READNOVALUE                 485
#define IDD_DATE_SELECT4                486
#define CG_IDD_MYDIALOGBAR20            487
#define IDD_CHARTDIALOG2                488
#define IDD_CHARTDIALOG3                489
#define IDD_DATASHOW1                   490
#define IDD_DATASHOW2                   498
#define IDD_USERINFO11                  499
#define CG_IDD_MYDIALOGBAR15            500
#define IDD_STAKEOUT                    501
#define IDD_CONDTION4                   502
#define IDD_CHARTDIALOG4                503
#define IDD_ZHULIUTIMESELECT            504
#define IDD_PARAMETERSET13              506
#define IDD_FENGBEISET                  509
#define IDD_TRANSFORMERDISP             512
#define IDD_CHANGEAMMETER               514
#define IDD_DATE_SELECT5                515
#define IDD_DATE_SELECT6                516
#define IDD_PARAMETERSET14              517
#define IDD_PARAMETERSET15              518
#define IDD_PARAMETERSET12              519
#define IDD_PARAMETERSET16              520
#define IDD_COMMSET1                    523
#define IDC_DATATREE                    1000
#define IDC_REMOTEDATACTL               1001
#define IDC_DISPLAY_STATIC              1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_DBGRID                      1004
#define CG_IDC_PROGDLG_PERCENT          1005
#define IDC_DBGRID2                     1005
#define IDC_EXIT                        1008
#define IDC_HELPS                       1009
#define IDC_DLG_LIST_AVAILABLE          1010
#define IDC_TRANFORMER                  1011
#define IDC_DLG_ADD                     1012
#define IDC_DATAOPERATION               1013
#define IDC_AMMETERINFO                 1014
#define IDC_DLG_ADD_ALL                 1015
#define IDC_USERINFO                    1016
#define IDC_DLG_REMOVE                  1017
#define IDC_DATAINFO                    1018
#define IDC_DLG_REMOVE_ALL              1019
#define IDC_DLG_LIST_CHOOSEN            1021
#define IDC_FIRSTRECORD                 1022
#define IDC_DLG_MOVE_UP                 1023
#define IDC_PREVIOUSRECORD              1024
#define IDC_DLG_MOVE_DOWN               1025
#define IDC_NEXTRECORD                  1026
#define IDC_PROFILE_NAME                1027
#define IDC_BUTTON4                     1028
#define IDC_OUTALL                      1029
#define IDC_PROFILE_NAME2               1030
#define IDC_BUTTON5                     1031
#define IDC_BUTTON6                     1032
#define IDC_SET                         1032
#define IDC_BUTTON7                     1036
#define IDC_CANCELSET                   1036
#define IDC_SEACHBROWSE                 1037
#define IDC_DATACHECK                   1038
#define IDC_EDIT1                       1039
#define IDC_HOST                        1040
#define IDC_EDIT34                      1040
#define IDC_HANDNO                      1041
#define IDC_EDIT35                      1041
#define IDC_INFO                        1042
#define IDC_EDIT36                      1042
#define IDC_EDIT2                       1043
#define IDC_EDIT37                      1043
#define IDC_ELCPRICE                    1044
#define IDC_EDIT38                      1044
#define IDC_DANGLE                      1045
#define IDC_REMARK                      1045
#define IDC_IMPULSE                     1046
#define IDC_EDIT3                       1047
#define IDC_PORT                        1050
#define IDC_HANDSTATIONNAME             1051
#define IDC_EDIT4                       1052
#define IDC_INTERVAL                    1053
#define IDC_DLG_LIST_AVAILABLE2         1054
#define IDC_EDIT5                       1055
#define IDC_END                         1056
#define IDC_DLG_ADD2                    1057
#define IDC_EDIT6                       1058
#define IDC_POSITION                    1059
#define IDC_SPACE                       1065
#define IDC_DLG_ADD_ALL2                1066
#define IDC_EDIT7                       1067
#define IDC_OWNERSHIP                   1068
#define IDC_CAPABILITY                  1069
#define IDC_DLG_REMOVE2                 1070
#define IDC_EDIT8                       1071
#define IDC_CURRENTDATA                 1072
#define IDC_DLG_REMOVE_ALL2             1073
#define IDC_EDIT9                       1074
#define IDC_RADIO1                      1075
#define IDC_POWERSTATION                1076
#define IDC_DL                          1077
#define IDC_RADIO43                     1077
#define IDC_DLG_LIST_CHOOSEN2           1078
#define IDC_RADIO45                     1078
#define IDC_EDIT10                      1079
#define IDC_RADIO2                      1082
#define IDC_RADIO49                     1083
#define IDC_DLG_MOVE_UP2                1084
#define IDC_EDIT11                      1085
#define IDC_RADIO3                      1086
#define IDC_DLG_MOVE_DOWN2              1087
#define IDC_RADIO38                     1087
#define IDC_EDIT12                      1088
#define IDC_CHECK1                      1089
#define IDC_RADIO7                      1090
#define IDC_CHECK35                     1090
#define IDC_ADDRESS                     1091
#define IDC_DLG_LIST_AVAILABLE3         1092
#define IDC_EDIT13                      1093
#define IDC_CHECK2                      1094
#define IDC_PRICE                       1095
#define IDC_CHECK36                     1095
#define IDC_RADIO11                     1096
#define IDC_GENERATRIXNO                1097
#define IDC_EMAIL                       1098
#define IDC_GENERATRIXNO2               1098
#define IDC_EDIT14                      1099
#define IDC_CHECK3                      1101
#define IDC_RADIO8                      1102
#define IDC_USERNO                      1103
#define IDC_RADIO17                     1104
#define IDC_CHECK4                      1105
#define IDC_RADIO18                     1106
#define IDC_EDIT15                      1107
#define IDC_DLG_ADD3                    1108
#define IDC_EDIT16                      1109
#define IDC_COMBO1                      1110
#define IDC_USECOMBO                    1110
#define IDC_COMBOKINDS                  1110
#define IDC_MOTHERCOMBO                 1110
#define IDC_USERCOMBO                   1110
#define IDC_COMBOPROTCOL                1110
#define IDC_LINECOMBO                   1111
#define IDC_MOTHERLINE                  1111
#define IDC_CHECK7                      1112
#define IDC_AMMTERCOMBO                 1112
#define IDC_MODULELINE                  1112
#define IDC_RADIO5                      1113
#define IDC_CHECK34                     1113
#define IDC_COMBOBIT                    1114
#define IDC_CHECK39                     1114
#define IDC_RADIO41                     1114
#define IDC_MOTHERCOMBO2                1114
#define IDC_LISTCOMBO                   1115
#define IDC_RADIO42                     1115
#define IDC_LINECOMBO2                  1115
#define IDC_RADIO19                     1116
#define IDC_CHECK44                     1116
#define IDC_COMBO                       1117
#define IDC_EDIT17                      1118
#define IDC_APPEARCOMBO                 1118
#define IDC_COMBO2                      1119
#define IDC_SOFTKIND                    1119
#define IDC_CHECK8                      1120
#define IDC_ELECTRICITYKIND             1121
#define IDC_CHECK37                     1121
#define IDC_COMBOPORT                   1122
#define IDC_CHECK38                     1122
#define IDC_RADIO10                     1123
#define IDC_CHECK40                     1123
#define IDC_RADIO20                     1124
#define IDC_CHECK41                     1124
#define IDC_EDIT18                      1125
#define IDC_CHECK42                     1125
#define IDC_CHECK9                      1126
#define IDC_CHECK43                     1126
#define IDC_POWERSTATIONNO              1127
#define IDC_CHECK45                     1127
#define IDC_RADIO21                     1128
#define IDC_DLG_ADD_ALL3                1129
#define IDC_EDIT19                      1130
#define IDC_BUTTON1                     1131
#define IDC_APPEARDATA                  1131
#define IDC_CLOSEDLG                    1131
#define IDC_PAUSE                       1131
#define IDC_CHECK10                     1132
#define IDC_BUTTON10                    1132
#define IDC_USEDESCRIBE                 1133
#define IDC_BUTTON11                    1133
#define IDC_PASSONE                     1134
#define IDC_BUTTON12                    1134
#define IDC_ANGLESET                    1135
#define IDC_BUTTON13                    1135
#define IDC_STOPELC                     1136
#define IDC_BUTTON14                    1136
#define IDC_DELETE                      1137
#define IDC_BUTTON15                    1137
#define IDC_STOP                        1138
#define IDC_BUTTON16                    1138
#define IDC_RADIO25                     1139
#define IDC_RANGER                      1139
#define IDC_BUTTON17                    1139
#define IDC_RESOLVE                     1140
#define IDC_BUTTON18                    1140
#define IDC_OTHERREFRESH                1141
#define IDC_BUTTON19                    1141
#define IDC_NETSEARCH                   1142
#define IDC_BUTTON20                    1142
#define IDC_BUTTON21                    1143
#define IDC_BUTTON22                    1144
#define IDC_BUTTON23                    1145
#define IDC_BUTTON24                    1146
#define IDC_BUTTON25                    1147
#define IDC_BUTTON26                    1148
#define IDC_BUTTON27                    1149
#define IDC_RADIO24                     1150
#define IDC_DLG_REMOVE3                 1151
#define IDC_BUTTON29                    1151
#define IDC_EDIT20                      1152
#define IDC_BUTTON30                    1152
#define IDC_BUTTON2                     1153
#define IDC_BUTTON31                    1153
#define IDC_CHECK11                     1154
#define IDC_BUTTON32                    1154
#define IDC_TABLEBOTTOMDATA             1155
#define IDC_PASSALL                     1156
#define IDC_BUTTON34                    1156
#define IDC_DANGLESET                   1157
#define IDC_BUTTON35                    1157
#define IDC_SENDELC                     1158
#define IDC_BUTTON36                    1158
#define IDC_RADIO26                     1159
#define IDC_BUTTON37                    1159
#define IDC_RESOLVE2                    1160
#define IDC_REFRESH                     1161
#define IDC_BUTTON39                    1161
#define IDC_NETADD                      1162
#define IDC_ADD                         1162
#define IDC_BUTTON40                    1162
#define IDC_DLG_REMOVE_ALL3             1163
#define IDC_BUTTON41                    1163
#define IDC_BUTTON42                    1164
#define IDC_BUTTON8                     1170
#define IDC_CHECK12                     1180
#define IDC_ADDTO                       1181
#define IDC_OLDUSERNO                   1182
#define IDC_READANGLE                   1183
#define IDC_RADIO27                     1184
#define IDC_OTHERSET                    1190
#define IDC_NETDELETE                   1191
#define IDC_EDIT21                      1192
#define IDC_STOALLPELC                  1193
#define IDC_DLG_LIST_CHOOSEN3           1194
#define IDC_BUTTON9                     1195
#define IDC_CHECK13                     1196
#define IDC_ORDER                       1197
#define IDC_ANGLESETB                   1198
#define IDC_CHECKCOMBOXTXT              1200
#define IDC_DATACOMBOTXT                1201
#define IDC_STOPCOMBOTXT                1202
#define IDC_TELEPHONETXT                1203
#define IDC_LOCALADDRESSTXT             1204
#define IDC_PORTTXT                     1205
#define IDC_IPADDRESSTXT                1206
#define IDC_HOSTTXT                     1207
#define IDC_HEX                         1211
#define IDC_SPIN                        1214
#define IDC_SPINHANDNO                  1215
#define IDC_SPIN30                      1215
#define IDC_SPINEVERY                   1215
#define ID_SETPARAMETER                 1216
#define IDC_SPINSCAN                    1216
#define IDC_SPIN31                      1216
#define IDC_SPINTIMEAGAIN               1217
#define IDC_SPIN32                      1217
#define ID_CANCELSET                    1217
#define IDC_SPINMINUTER                 1218
#define IDC_SPINSCANTIMES               1218
#define IDC_SPIN33                      1218
#define IDC_SPINTIMES                   1219
#define IDC_SPIN34                      1219
#define ID_SETINTERVAL                  1220
#define IDC_SPIN35                      1220
#define IDC_EDIT_OTHERTIME              1221
#define IDC_GIF                         1222
#define IDC_PHONESELECT                 1223
#define IDC_SPIN1                       1224
#define IDC_SPIN2                       1225
#define IDC_SPIN3                       1226
#define IDC_SPIN4                       1227
#define IDC_SPIN5                       1228
#define IDC_EYES                        1229
#define IDC_SPIN6                       1229
#define IDC_APPEARONLY                  1230
#define IDC_SPIN7                       1230
#define IDC_LISTS                       1231
#define IDC_SPIN8                       1231
#define IDC_SPIN9                       1232
#define IDC_SPIN10                      1233
#define IDC_SPIN11                      1234
#define IDC_SPIN12                      1235
#define IDC_SPIN13                      1236
#define IDC_SPIN14                      1237
#define IDC_SPIN15                      1238
#define IDC_SPIN16                      1239
#define IDC_SPIN17                      1240
#define IDC_SPIN18                      1241
#define IDC_SPIN19                      1242
#define IDC_SPIN20                      1243
#define IDC_SPIN21                      1244
#define IDC_SPIN22                      1245
#define IDC_SPIN23                      1246
#define IDC_COMBO4                      1246
#define IDC_SPIN24                      1247
#define ID_SETPAR                       1247
#define IDC_SPIN25                      1248
#define IDC_SPIN26                      1249
#define IDC_PRINTREPORTS                1249
#define IDC_SPIN27                      1250
#define IDC_LISTSS                      1250
#define IDC_SPIN28                      1251
#define IDC_COMBO5                      1251
#define IDC_SUPPORTBREAK                1251
#define IDC_SPIN29                      1252
#define IDC_COMBO6                      1253
#define IDC_COMBO7                      1254
#define IDC_COMBO8                      1255
#define IDC_COMBO9                      1256
#define IDC_COMBO10                     1257
#define IDC_COMBO11                     1258
#define IDC_IPADDRESS1                  1258
#define IDC_COMBO12                     1259
#define ID_ADD                          1259
#define IDC_COMBO13                     1260
#define IDC_PHONENO                     1260
#define IDC_COMBO14                     1261
#define IDC_COMBO15                     1262
#define IDC_COMBO16                     1263
#define IDC_ADDSTATION                  1263
#define IDC_COMBO17                     1264
#define IDC_MARKET                      1264
#define IDC_COMBO18                     1265
#define IDC_COMPUTERLINE                1265
#define IDC_COMBO19                     1266
#define ID_SAVEFILE                     1266
#define IDC_COMBO20                     1267
#define IDC_COMBO21                     1268
#define IDC_COMBO22                     1269
#define IDC_DATETIMEPICKERBEGIN         1269
#define IDC_COMBO23                     1270
#define IDC_DATETIMEPICKEREND           1270
#define IDC_COMBO24                     1271
#define IDC_SSTAB1                      1271
#define IDC_COMBO25                     1272
#define IDC_AUTODIAL                    1272
#define IDC_SSTAB4                      1272
#define IDC_COMBO26                     1273
#define IDC_SPINTIME                    1273
#define IDC_SSTAB5                      1273
#define IDC_COMBO27                     1274
#define IDC_COMBO28                     1275
#define IDC_STATIC1                     1275
#define IDC_COMBO29                     1276
#define IDC_STATIC2                     1276
#define IDC_COMBO30                     1277
#define IDC_STATIC3                     1277
#define IDC_COMBO31                     1278
#define ID_DATAINTO                     1278
#define IDC_STATIC28                    1278
#define IDC_COMBO32                     1279
#define IDC_COMBO33                     1280
#define IDC_DATAEDIT                    1280
#define IDC_MAYBEDATA                   1281
#define IDC_CHECK                       1282
#define IDC_STATIC4                     1283
#define IDC_STATIC5                     1284
#define IDC_STATIC6                     1285
#define IDC_STATIC7                     1286
#define IDC_STATIC8                     1287
#define IDC_STATIC9                     1288
#define IDC_SSTAB2                      1290
#define IDC_SSTAB3                      1291
#define IDC_SELECTDBGRID                1292
#define IDC_SSTABDATA                   1293
#define IDC_NOVOICE                     1294
#define IDC_LISTSSTAB                   1295
#define IDC_SYNCHRONIZATION             1296
#define IDC_CONNECT                     1297
#define IDC_ELCNO                       1298
#define IDC_AMMETTERTYPE                1299
#define IDC_SETLOCAL                    1300
#define IDC_ELCTYPE                     1300
#define IDC_REFRESHS                    1301
#define IDC_SENDANGLE                   1301
#define IDC_RADIO30                     1302
#define IDC_STATIC10                    1302
#define IDC_EDIT22                      1303
#define IDC_STATIC11                    1303
#define IDC_SENDALLELC                  1304
#define IDC_STATIC12                    1304
#define IDC_DLG_MOVE_UP3                1305
#define IDC_STATIC13                    1305
#define IDC_DBGRID1                     1306
#define IDC_STATIC14                    1306
#define IDC_CHECK14                     1307
#define IDC_STATIC15                    1307
#define IDC_READANGLEB                  1308
#define IDC_STATIC16                    1308
#define IDC_RADIO31                     1309
#define IDC_STATIC17                    1309
#define IDC_EDIT23                      1310
#define IDC_STATIC18                    1310
#define IDC_DLG_MOVE_DOWN3              1311
#define IDC_STATIC19                    1311
#define IDC_REMOTEDATACTL1              1312
#define IDC_STATIC20                    1312
#define IDC_RADIO14                     1313
#define IDC_ANGLESETC                   1314
#define IDC_STATIC21                    1314
#define IDC_RADIO32                     1315
#define IDC_STATIC22                    1315
#define IDC_EDIT24                      1316
#define IDC_STATIC23                    1316
#define IDC_CHECK17                     1317
#define IDC_STATIC24                    1317
#define IDC_DLG_LIST_AVAILABLE4         1318
#define IDC_STATIC25                    1318
#define IDC_LIST1                       1319
#define IDC_UPVALUE                     1320
#define IDC_DOWNVALUE                   1321
#define IDC_STATIC26                    1322
#define IDC_STATIC27                    1323
#define IDC_CHECK101                    1324
#define IDC_RADIO15                     1325
#define IDC_CHECK102                    1325
#define IDC_READANGLEC                  1326
#define IDC_CHECK103                    1326
#define IDC_RADIO33                     1327
#define IDC_CHECK104                    1327
#define IDC_EDIT25                      1328
#define IDC_CHECK105                    1328
#define IDC_LIST                        1329
#define IDC_CHECK106                    1329
#define IDC_CHECK18                     1330
#define IDC_CHECK107                    1330
#define IDC_DLG_ADD4                    1331
#define IDC_CHECK108                    1331
#define IDC_BUTTON3                     1332
#define IDC_CHECK109                    1332
#define IDC_OUTONE                      1333
#define IDC_CHECK110                    1333
#define IDC_TOTAL                       1334
#define IDC_CHECK111                    1334
#define IDC_READANGLECD                 1335
#define IDC_CHECK112                    1335
#define IDC_CHECK113                    1336
#define IDC_CHECK114                    1337
#define IDC_CHECK115                    1338
#define IDC_CHECK116                    1339
#define IDC_CHECK117                    1340
#define IDC_CHECK118                    1341
#define IDC_CHECK119                    1342
#define IDC_CHECK120                    1343
#define IDC_CHECK121                    1344
#define IDC_COMPUTER                    1345
#define IDC_CHECK122                    1345
#define IDC_SETTITLE                    1346
#define IDC_CHECK123                    1346
#define IDC_EDIT26                      1347
#define IDC_CHECK124                    1347
#define IDC_CHECK19                     1348
#define IDC_CHECK125                    1348
#define IDC_DLG_ADD_ALL4                1349
#define IDC_CHECK126                    1349
#define IDC_LIST2                       1350
#define IDC_CHECK127                    1350
#define IDC_CHECK128                    1351
#define IDC_CHECK129                    1352
#define IDC_CHECK130                    1353
#define IDC_CHECK131                    1354
#define IDC_CURVE                       1355
#define IDC_COMPUTERS                   1356
#define IDC_EDIT27                      1357
#define IDC_CHECK20                     1359
#define IDC_DLG_REMOVE4                 1360
#define IDC_RADIO4                      1361
#define IDC_DELETEPHONE                 1362
#define IDC_RADIO37                     1362
#define IDC_EDIT28                      1363
#define IDC_MESSAGE                     1363
#define IDC_DATATOREPORT                1364
#define IDC_ALLSET                      1364
#define IDC_CHECK21                     1365
#define IDC_ALLCLEAR                    1365
#define IDC_TEXT                        1366
#define IDC_DLG_REMOVE_ALL4             1367
#define IDC_STATIC29                    1367
#define IDC_RADIO9                      1368
#define IDC_EDIT29                      1369
#define IDC_RADIO48                     1369
#define IDC_ADDPHONE                    1370
#define IDC_BAKGENERATRIXNO             1370
#define IDC_CHECK22                     1371
#define IDC_BAKLINENO                   1371
#define IDC_DLG_LIST_CHOOSEN4           1372
#define IDC_BAKMOTHERCOMBO              1372
#define IDC_BAKLINECOMBO                1373
#define IDC_SAVEYEARS                   1374
#define IDC_SETYEARS                    1375
#define IDC_READYEARS                   1376
#define IDC_FENGSET                     1377
#define IDC_TOTALSET                    1378
#define IDC_APPEARSTR                   1379
#define IDC_LISTDATA                    1380
#define IDC_MULTIPLE                    1380
#define IDC_CHAAMMETER                  1381
#define IDC_BTSEARCH                    1382
#define IDC_MODULENOOLD                 1383
#define IDC_AMMETERNOOLD                1384
#define IDC_YGDDOLD                     1385
#define IDC_HANDYGDDOLD                 1386
#define IDC_WGDDOLD                     1387
#define IDC_HANDWGDDOLD                 1388
#define IDC_FDLOLD                      1389
#define IDC_SAVEBMP                     1390
#define IDC_JFDLOLD                     1390
#define IDC_RADIO35                     1391
#define IDC_GDLOLD                      1391
#define IDC_EDIT30                      1392
#define IDC_PDLOLD                      1392
#define IDC_CHECK23                     1393
#define IDC_TIMEEVERY                   1393
#define IDC_DLG_MOVE_UP4                1394
#define IDC_TESTTIMES                   1394
#define IDC_WGSPACE                     1394
#define IDC_CHECK5                      1395
#define IDC_UP                          1395
#define IDC_PRINTBMP                    1396
#define IDC_DOWN                        1396
#define IDC_EDIT31                      1397
#define IDC_CHECK24                     1398
#define IDC_QUICKREAD                   1398
#define IDC_DLG_MOVE_DOWN4              1399
#define IDC_CHECK6                      1410
#define IDC_SETXTITLE                   1411
#define IDC_EDIT32                      1412
#define IDC_CHECK25                     1413
#define IDC_DLG_LIST_AVAILABLE5         1414
#define IDC_CHECK15                     1415
#define IDC_SETYTITLE                   1416
#define IDC_EDIT33                      1417
#define IDC_CHECK26                     1418
#define IDC_DLG_ADD5                    1419
#define IDC_CHECK16                     1420
#define IDC_CHECK27                     1421
#define IDC_DLG_ADD_ALL5                1422
#define IDC_RADIO6                      1423
#define IDC_CHECK28                     1424
#define IDC_RADIO44                     1424
#define IDC_DLG_REMOVE5                 1425
#define IDC_RADIO47                     1425
#define IDC_RADIO34                     1427
#define IDC_CHECK29                     1428
#define IDC_DLG_REMOVE_ALL5             1428
#define IDC_TRANSFORMERNO               1429
#define IDC_CHECK30                     1430
#define IDC_DLG_LIST_CHOOSEN5           1431
#define IDC_TRANSFORMERMODEL            1432
#define IDC_CHECK31                     1433
#define IDC_DLG_MOVE_UP5                1434
#define IDC_CAPABILOITY                 1435
#define IDC_CHECK32                     1436
#define IDC_DLG_MOVE_DOWN5              1437
#define IDC_CTSCALE                     1438
#define IDC_CHECK33                     1439
#define IDC_LASTRECORD                  1440
#define IDC_ADDRECORD                   1441
#define IDC_DELRECORD                   1442
#define IDC_COMBODATAINFO               1443
#define IDC_SAVEDATA                    1444
#define IDC_SEARCH                      1445
#define IDC_DIVIDESQL                   1446
#define IDC_CHULI                       1447
#define IDC_TOTALSQLS                   1448
#define IDC_REMOTEDATACTLS              1449
#define IDC_OPERATE                     1450
#define IDC_SEND                        1451
#define IDC_VALUE                       1452
#define IDC_CLEAR                       1453
#define IDC_DEFAULTBOX                  1454
#define IDC_DATETIMEPICKER              1455
#define IDC_AMMETTERNO                  1456
#define IDC_AMMETTERMODEL               1457
#define IDC_AMMETTERREMARK              1457
#define IDC_MANUFACTURER                1458
#define IDC_IMPLUSE                     1459
#define IDC_LINE                        1460
#define IDC_MODULENO                    1461
#define IDC_NAME                        1462
#define IDC_TELEPHONE                   1463
#define IDC_AMMETERNO                   1463
#define IDC_INSTALLDATE                 1464
#define IDC_RANGE                       1465
#define IDC_LINENO                      1466
#define IDC_FIELDLIST                   1467
#define IDC_LINENO2                     1467
#define IDC_RESULT                      1468
#define IDC_LABEL                       1469
#define IDC_MODIFY                      1470
#define IDC_COMEIN                      1471
#define IDC_OLDPASSWORD                 1472
#define IDC_NEWPASSWORD                 1473
#define IDC_LASTMONTHVALUE              1474
#define IDC_NEWPASSOK                   1475
#define IDC_READTABLETIME               1476
#define IDC_READTABLETIME2              1477
#define IDC_CORRESPONDINGPROTOCOL       1478
#define IDC_STOPPING                    1479
#define IDC_COMMUNICATIONSTATE          1480
#define IDC_USESTATE                    1485
#define IDC_CONTENTUINT                 1486
#define IDC_DBGRIDS                     1487
#define IDC_OWEUSER                     1488
#define IDC_WGGL                        1489
#define IDC_EDIT_BROADTIME              1490
#define IDC_TDCS                        1491
#define IDC_EDIT_BROADINTERVAL          1492
#define IDC_YGGL                        1495
#define IDC_EDIT_LOCALTIME              1496
#define IDC_EDIT_BROADTIMES             1497
#define IDC_GLYS                        1498
#define IDC_DY                          1499
#define IDC_JZ                          1501
#define IDC_DIAL                        1502
#define IDC_DYJBL                       1503
#define IDC_AUTOREPLY                   1504
#define IDC_STATUS                      1506
#define IDC_XL                          1507
#define IDC_DISCONNECT                  1508
#define IDC_DIAL2                       1509
#define IDC_DYHGL                       1510
#define IDC_MSCOMM                      1511
#define IDC_RANGESTR                    1512
#define IDC_YGDD                        1513
#define IDC_WGDD                        1514
#define IDC_485MSCOMM                   1515
#define IDC_HANDYGDD                    1516
#define IDC_PRINTREPORT                 1517
#define IDC_HANDWGDD                    1518
#define IDC_BEGINTIME                   1519
#define IDC_ENDTIME                     1520
#define IDC_TITLE                       1521
#define IDC_TITLECOMBO                  1522
#define IDC_XTITLE                      1523
#define IDC_COMPNAME                    1524
#define IDC_YTITLE                      1525
#define IDC_COMPANY                     1526
#define IDC_COMBOFIELD                  1527
#define IDC_RADIO12                     1528
#define IDC_RADIO13                     1529
#define IDC_RADIO36                     1530
#define IDC_ELCKIND                     1531
#define IDC_TIMEG                       1532
#define IDC_RADIO46                     1532
#define IDC_TIMES                       1533
#define IDC_SANGLE                      1534
#define IDC_STATICS                     1535
#define IDC_SANGLEB                     1536
#define IDC_TREE1                       1537
#define IDC_SANGLEC                     1538
#define IDC_FINDSTRING                  1539
#define IDC_RADIO16                     1540
#define IDC_NOOk                        1541
#define IDC_RADIO39                     1541
#define IDC_ZHULIUT                     1542
#define IDC_RADIO40                     1542
#define IDC_MINUTER                     1543
#define IDC_READLABEL                   1544
#define IDC_BEGIN                       1550
#define IDC_ANGLE                       1556
#define IDC_RADIO22                     1557
#define IDC_RADIO23                     1558
#define IDC_RADIO28                     1559
#define IDC_RADIO29                     1560
#define IDC_NOAPPEAR                    1561
#define IDC_APPEARINLIST                1562
#define IDC_MSCHART                     1563
#define IDC_CHECKCOMBOX                 1564
#define IDC_DATACOMBO                   1565
#define IDC_STOPCOMBO                   1566
#define IDC_IA                          1567
#define IDC_IB                          1568
#define IDC_IC                          1569
#define IDC_UA                          1570
#define IDC_UB                          1571
#define IDC_UC                          1572
#define IDC_PROTOCOL                    1573
#define IDC_SHOWLEGEND                  1574
#define IDC_INTENSION                   1574
#define IDC_JFDL                        1574
#define ID_START                        1575
#define IDC_FDL                         1575
#define IDC_SHOWLABEL                   1576
#define IDC_GDL                         1576
#define IDC_SHOWSTASLINE                1577
#define IDC_PDL                         1577
#define IDC_IPADDRESS                   1578
#define IDC_SHOWVALUE                   1579
#define IDC_LOCALADDRESS                1580
#define IDC_SHOWXLABEL                  1580
#define IDC_WINSOCK                     1581
#define IDC_SSTAB                       1582
#define IDC_COMBOPORTTXT                1583
#define IDC_COMBOBITTXT                 1584
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_MENUITEM32771                32771
#define ID_COMPANYREPORT                32772
#define ID_SUBSTATIONREPORT             32773
#define ID_SHOWLIST                     32773
#define ID_LINEREPORT                   32774
#define ID_ASCENDING                    32775
#define ID_BUTTON32776                  32776
#define ID_DESC                         32778
#define ID_BUTTON32779                  32779
#define ID_STOPRUN                      32779
#define ID_BUTTON32781                  32781
#define ID_TESTREADTABLE                32783
#define ID_INDEEDREADTABLE              32784
#define ID_BREADORDER                   32785
#define ID_READDATA                     32786
#define ID_MENUITEM32787                32787
#define ID_SEARCHBROWSE                 32788
#define ID_MENUITEM32790                32790
#define ID_MENUITEM32791                32791
#define ID_TABLEBROWSE                  32792
#define ID_REPORT                       32793
#define ID_COMMUNICATION                32802
#define ID_USERINFO                     32803
#define ID_TRANFORMER                   32804
#define ID_AMMETERINFO                  32805
#define ID_DEFENDTABLE                  32809
#define ID_DATATABLE                    32810
#define ID_CURVE                        32811
#define ID_BUTTON32819                  32819
#define ID_RECORDOPERATE                32821
#define ID_OWEMONEY                     32822
#define ID_OPENREPORTFILE               32824
#define ID_NEWREPORT                    32827
#define ID_PRICE                        32828
#define ID_DATAPASS                     32829
#define ID_CONNECTSUCCESS               32830
#define ID_TESTREADAMTER                32831
#define ID_STOPEXAM                     32832
#define ID_RECYCLE                      32833
#define ID_ANGLESET                     32834
#define ID_PHASETEST                    32835
#define ID_DATAAPPEAR                   32839
#define ID_APPEARPREVDATA               32864
#define ID_HIDEDATA                     32865
#define ID_CLEARDATA                    32866
#define ID_SELECTITEM                   32867
#define ID_BUTTON32882                  32882
#define ID_BUTTON32892                  32892
#define ID_AUTOREAD                     32893
#define ID_BUTTON32901                  32901
#define ID_TIMECHECK                    32906
#define ID_HUNANPASS                    32907
#define ID_MODIFYSTATUS                 32908
#define ID_LST_DELETE                   32910
#define ID_LST_SAVE                     32911
#define ID_AUTOREADSET                  32912
#define ID_BREAkSOMEDAY                 32913
#define ID_BREAKEVERYDAY                32914
#define ID_PASSUSERDATA                 32916
#define ID_TEST                         32917
#define ID_SHOWDIALOGBAR                32918
#define ID_APPEARSELECTDATA             32919
#define ID_SAVEREPORTAS                 32920
#define ID_REMOTEMODIFY                 32921
#define ID_GETDATAFROMWS                32922
#define ID_LOCALMODIFY                  32923
#define ID_GETDATAFROMLONG              32924
#define ID_LST_DELETERANGE              32925
#define ID_SETDIAL                      32927
#define ID_SETTCPIP                     32928
#define ID_REPORTFONT                   32930
#define ID_DELETEMODULE                 32931
#define ID_CLOSEREPORT                  32932
#define ID_TIMESEARCH                   32933
#define ID_ZHENSHIMODIFY                32936
#define ID_ZHULIUMODIFY                 32937
#define ID_DELETE_ALL_HISTORY           32939
#define ID_GETFILE                      32940
#define ID_STOPORSEND                   32943
#define ID_LISTSELECT                   32946
#define ID_DISCONNECTTIME               32949
#define ID_CHECKEQAUL                   32950
#define ID_XIANGCHANGE                  32951
#define ID_CHECKLINESTATUS              32952
#define ID_FINDREPEATRECORDS            32953
#define ID_FAUTOREADSET                 32954
#define ID_CANCELAUTOZHULIU             32956
#define ID_CHANGEAMMETER                32957
#define ID_MODIFYPROTCOL                32958
#define ID_WXCHECKSTATUS                32959
#define ID_WUGONGPARAMETER              32960
#define ID_WUGONGDEAL                   32961
#define ID_DRFROMACCESS                 32964

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        486
#define _APS_NEXT_COMMAND_VALUE         32965
#define _APS_NEXT_CONTROL_VALUE         1400
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
