#if !defined(AFX_VCFRAME_H__CC6FCF64_7A22_4395_89FA_026CBAB6BEB9__INCLUDED_)
#define AFX_VCFRAME_H__CC6FCF64_7A22_4395_89FA_026CBAB6BEB9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CVcColor;

/////////////////////////////////////////////////////////////////////////////
// CVcFrame wrapper class

class CVcFrame : public COleDispatchDriver
{
public:
	CVcFrame() {}		// Calls COleDispatchDriver default constructor
	CVcFrame(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVcFrame(const CVcFrame& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	CVcColor GetFrameColor();
	CVcColor GetSpaceColor();
	float GetWidth();
	void SetWidth(float newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VCFRAME_H__CC6FCF64_7A22_4395_89FA_026CBAB6BEB9__INCLUDED_)
